# **데이터 전처리 - 데이터탐색, 결측치처리**

- 데이터 분석/AI 모델링을 위하여 데이터를 정제하는 전처리 과정은 아래와 같습니다.
    - 첫번째, 데이터 탐색하기
    - 두번째, 결측치 처리하기
    - 세번째, 이상치 처리하기
    - 네번째, Feature Engineering 
- 데이터 전처리 , 첫번째 파트로 데이터 탐색과 결측치 처리에 대해서 배워 보도록 하겠습니다.
- 추가로, 데이터 탐색시 숫자형 컬럼이 문자형 컬럼으로 되어 있어, 이럴경우 어떻게 처리하는지도 배우도록 하겠습니다.

<br>

## **0. 필요 라이브러리와 데이터 불러오기**

In [1]:
# 필요한 라이브러리 불러오기
import pandas as pd
import numpy as np

# warning 경고 제거하기
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 판다스 옵션을 사용해서 화면에 보기 좋기 보이게 하기

pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option("display.max_columns", 999)

In [3]:
# sc_cust_info_txn_v1.5.csv 데이터 파일을 읽고 df 데이터프레임에 저장합니다.

df = pd.read_csv("../sc_cust_info_txn_v1.5.csv")

In [47]:
# 저장된 df 데이터프레임 확인하기
df

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.00,792.00,1584.00,0.00,0.00,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.00,90.00,180.00,0.00,0.00,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.00,2526.00,6983.00,0.00,6981.00,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.73,2331.71,6750.47,0.00,6508.80,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.00,0.00,4502.00,0.00,4507.70,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.10,194.41,643.10,0.00,852.55,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.67,2069.95,10605.93,0.00,10603.93,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.20,1206.00,0.00,1212.00,0.00,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.00,942.00,1884.00,0.00,0.00,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.90,365.54,1839.90,0.00,1919.80,N

<br>

## **1. 데이터 탐색하기**

### **데이터 확인하기**
Dataframe에서 제공하는 메소드를 활용하여 데이터의 구성을 확인합니다.    
info는 데이터 구성과 특성을 확인해 볼 수 있습니다

In [72]:
# 데이터프레임의 구성과 특성을 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   str
 4   sex_type            9930 non-null   str
 5   age                 9930 non-null   str
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   str
 8   npay_yn             9930 non-null   str
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   str
dtypes: float64(5), int64(4), str(6)
memory usage: 1.1 MB

In [61]:
# df 데이터프레임의 앞 5개 라인 확인하기
df.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.00,792.00,1584.00,0.00,0.00,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.00,90.00,180.00,0.00,0.00,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.00,2526.00,6983.00,0.00,6981.00,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.73,2331.71,6750.47,0.00,6508.80,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.00,0.00,4502.00,0.00,4507.70,N

In [62]:
# df 데이터프레임의 뒤 5개 라인 확인하기
df.tail()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.10,194.41,643.10,0.00,852.55,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.67,2069.95,10605.93,0.00,10603.93,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.20,1206.00,0.00,1212.00,0.00,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.00,942.00,1884.00,0.00,0.00,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.90,365.54,1839.90,0.00,1919.80,N

In [73]:
# df 데이터프레임에 대해서 기술적 통계 확인합니다. 
# 연속형 컬럼에 대해서 평균, 표준편차, 최소값, 최대값등을 출력합니다.

df.describe()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
count,9930.00,9930.00,9930.00,9930.00,9930.00,9930.00,9930.00,9930.00,9930.00
mean,202006.00,20200630.00,10001.37,1.52,11817.74,1897.54,6395.26,849.62,4624.90
std,0.00,0.00,1.61,15.40,139782.18,12353.42,83461.38,12351.24,4561.05
min,202006.00,20200630.00,10001.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,202006.00,20200630.00,10001.00,1.00,3624.50,324.00,1260.00,0.00,0.00
50%,202006.00,20200630.00,10001.00,1.00,8284.47,1593.31,4768.62,0.00,3959.32
75%,202006.00,20200630.00,10001.00,1.00,13720.00,2308.36,7982.00,1006.12,7741.01
max,202006.00,20200630.00,10010.00,905.00,12815682.13,1188998.30,7689409.28,1208497.66,64947.09

### <b>필요한 컬럼만 추출하기</b>
수집한 데이터의 컬럼이 너무 많을 경우 데이터 처리에 불필요한 시간과 자원이 계속 소모 되기에,     
이번 수업에서는 필요한 컬럼만 추출하여 데이터처리를 하도록 하겠습니다.    
실제 분석/모델링에서는 어떤 컬럼이 중요할지 알수 없기 떄문에 자원이 가능한 많은 데이터를 가지고 하셔도 좋습니다.

In [4]:
# 데이터 처리에 필요한 10개 항목만 추출하겠습니다. 
# 고객등급(cust_class), 성별(sex_type), 나이(age), 사용서비스수(efct_svc_count), 서비스중지여부 (dt_stop_yn), 미납여부(npay_yn)
# 3개월 평균 요금(r3m_avg_bill_amt), A서비스 3개월 평균요금(r3m_A_avg_arpu_amt), B서비스 3개월 평균요금(r3m_B_avg_arpu_amt), 해지여부(termination_yn)
# 10개의 필요한 컬럼들을 리스트에 넣으면 되고, 결과를 cust 데이터프레임에 저장합니다. 

cust = df[ ["cust_class","sex_type","age","efct_svc_count","dt_stop_yn",
         "npay_yn","r3m_avg_bill_amt","r3m_A_avg_arpu_amt","r3m_B_avg_arpu_amt", "termination_yn"] ]

In [5]:
# cust 데이터프레임의 앞 5개 데이터 확인
# 10개 컬럼으로 구성되었고 전보다 보기 좋아 보이네요.

cust.head()

,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,termination_yn
0,C,F,28,0,N,N,2640.00,792.00,1584.00,Y
1,_,_,_,1,N,N,300.00,90.00,180.00,Y
2,E,F,24,1,N,N,16840.00,2526.00,6983.00,N
3,F,F,32,1,N,N,15544.73,2331.71,6750.47,N
4,D,M,18,1,N,N,4700.00,0.00,4502.00,N

실습의 편의를 위해 컬럼명을 조금 더 간결하고 직관적으로 변경해 보겠습니다.     
실제 여러명이 동시에 진행하는 분석 프로젝트나 모델링에서는 정해진 네이밍 룰에 따라 변경하거나 원천 컬럼명을 그대로 사용하는 것이 좋습니다.

In [6]:
# 컬럼명을 간결하고 직관적으로 변경해 보겠습니다. 
# rename 함수를 사용하여 컬럼명 변경합니다. 

cust = cust.rename( columns = {"cust_class" : 'class',          # 고객등급
                             "sex_type":'sex',                # 성별
                             "efct_svc_count":'service',      # 사용 서비스수
                             "dt_stop_yn":'stop',             # 서비스 중지 여부
                             "npay_yn":'npay',                # 미납 여부
                             "r3m_avg_bill_amt":'avg_bill',   # 3개월 평균 요금
                             "r3m_A_avg_arpu_amt":"A_bill",   # A서비스 3개월 평균요금
                             "r3m_B_avg_arpu_amt":'B_bill',   # B서비스 3개월 평균요금
                             "termination_yn":'termination' } # 해지 여부
                )

In [7]:
# cust 데이터프레임의 이름 변경 확인하기
# 컬럼이름이 간결해져서 보기 좋네요.

cust.head()

  class sex age  service stop npay  avg_bill  A_bill  B_bill termination
0     C   F  28        0    N    N   2640.00  792.00 1584.00           Y
1     _   _   _        1    N    N    300.00   90.00  180.00           Y
2     E   F  24        1    N    N  16840.00 2526.00 6983.00           N
3     F   F  32        1    N    N  15544.73 2331.71 6750.47           N
4     D   M  18        1    N    N   4700.00    0.00 4502.00           N

In [77]:
# cust 데이터프레임의 기술적 통계정보 보기
# avg_bill, A_bill, B_bill 컬럼의 max 값이 굉장히 큰것을 알수 있습니다.

cust.describe()

       service    avg_bill     A_bill     B_bill
count  9930.00     9930.00    9930.00    9930.00
mean      1.52    11817.74    1897.54    6395.26
std      15.40   139782.18   12353.42   83461.38
min       0.00        0.00       0.00       0.00
25%       1.00     3624.50     324.00    1260.00
50%       1.00     8284.47    1593.31    4768.62
75%       1.00    13720.00    2308.36    7982.00
max     905.00 12815682.13 1188998.30 7689409.28

<br>

### <b>데이터 타입 변경하기</b>
데이터를 불러온 후에는 반드시 데이터 타입을 확인해 주시는것이 좋습니다.    
숫자형 데이터가 문자형으로 지정되어 있거나 혹은 그반대의 경우 원하는 데이터 처리 결과가 도출 되지 않을 수 있습니다.

In [10]:
# cust 데이터프레임의 구성과 정보에 대해 확인해 보겠습니다.
# 10개의 컬럼으로 구성되었으며, 컬럼 이름이 간결해 진걸 확인할수 있습니다.
# 그런데, age 컬럼의 타입이 숫자형이 아니라  object 문자열로 나오고 있습니다.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        9930 non-null   str
 1   sex          9930 non-null   str
 2   age          9930 non-null   str
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 775.9 KB

In [11]:
# 실제 age 컬럼의 값들을 확인해 보겠습니다.
# age 컬럼의 값들을 보니 '_'가 있네요. 
# 그래서 판다스에서 age 컬럼을 숫자로 보지 않고 문자열 object로 파악했네요

cust[ 'age' ].head()

0    28
1     _
2    24
3    32
4    18
Name: age, dtype: str

In [12]:
# astype() 함수를 활용허여 age 컬럼의 타입을 숫자형으로 변경해 보겠습니다. 
# 강제로 숫자 타입을 변경하려고 했는데, 에러가 발생합니다. 
# 왜냐하면, '_' 글자를 숫자 0~9 중에 어떤걸로 변경할수가 없으니 에러가 당근 발생합니다. 

cust[ 'age' ].astype( 'int' )

ValueError: invalid literal for int() with base 10: '_'

In [13]:
# age 컬럼의 '_' 값을 뭐로 바꿔야 할지 모르니
# 문제 해결을 위해 replace 함수를 활용해서 age 컬럼의 '_' 문자값을 NaN 값으로 치환해 보겠습니다. 
# 치환된 결과를 다시 cust 데이터프레임에 저장 합니다. 

cust = cust.replace("_", np.nan)

In [14]:
# 잘 처리되었는지 확인 위해서 age 컬럼의 내용을 보겠습니다. 
# 결과를 보니 기존의 '_' 문자열이 NaN null로 변경됨을 확인할수 있습니다. 잘 치환되었네요.

cust[ 'age' ].head()

0     28
1    NaN
2     24
3     32
4     18
Name: age, dtype: str

In [15]:
# 다시 cust 데이터프레임의 구성과 정보에 대해 확인해 보겠습니다.
# 아직도, age 컬럼의 타입이 object 문자열로 나오고 있네요.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8529 non-null   str
 1   sex          9249 non-null   str
 2   age          9178 non-null   str
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 775.9 KB

In [16]:
# 다시, astype 함수를 활용해서 age 컬럼의 타입을 숫자형으로 변경해 보겠습니다. 
# NaN의 경우 int type을 지원하지 않아 float type으로 변경합니다. 

cust = cust.astype( {'age': float } )  # cust[ 'age' ].astype('float') 동일한 결과 나옴.

In [17]:
# astype 실행 결과를 확인해 보겠습니다.
# age 컬럼 타입이 float 변경됨을 확인할수 있습니다.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8529 non-null   str
 1   sex          9249 non-null   str
 2   age          9178 non-null   float64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 775.9 KB

In [18]:
# cust 데이터프레임의 age 컬럼의 값들도 확인해 보겠습니다. 
# age 컬럼의 값들이 실수형(float)로 나오고 있음을 확인할수 있네요.

cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [19]:
# 이번에는 loc 함수를 사용해서 원하는 행과 컬럼을 접근해 보겠습니다. 
# cust 데이터프레임의 첫번째 행 접근하기 : 시리즈 형태로 보입니다. 

cust.loc[ 0 ]

class               C
sex                 F
age             28.00
service             0
stop                N
npay                N
avg_bill      2640.00
A_bill         792.00
B_bill        1584.00
termination         Y
Name: 0, dtype: object

In [20]:
# 이번에는 loc 함수를 사용해서 원하는 행과 컬럼을 접근해 보겠습니다. 
# cust 데이터프레임의 [1 ,3, 5] 인덱스 접근하기 : 1, 3,,5 인덱스의 행라인을 볼수 있습니다. 

cust.loc[ [ 1, 3, 5 ] ]

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
5     C    F 78.00        1    N    N   1361.80 1174.00    0.00           N

In [21]:
# 이번에는 loc 함수를 사용해서 원하는 행과 컬럼을 접근해 보겠습니다. 
# cust 데이터프레임의 [1 ,3, 5] 인덱스의 class 컬럼만 확인해 보겠습니다. : 시리즈 형태로 보입니다. 

cust.loc[ [ 1, 3, 5 ] , 'class' ]

1    NaN
3      F
5      C
Name: class, dtype: str

In [22]:
# 이번에는 loc 함수를 사용해서 원하는 행과 컬럼을 접근해 보겠습니다. 
# cust 데이터프레임의 [1 ,3, 5] 인덱스의 class 컬럼,service 컬럼, avg_bill컬럼을 접근해 보겠습니다.
# loc 함수를 많이 사용하오니, 반드시 익혀서 잘 사용하시길 바랍니다.

cust.loc[ [ 1, 3, 5 ] , [ 'class',  'service',  'avg_bill' ] ]

  class  service  avg_bill
1   NaN        1    300.00
3     F        1  15544.73
5     C        1   1361.80

<br>

## **2. 결측치 처리하기**
- 결측치 : Missing Value로 데이터에 값이 없는 것을 의미. NA, Null, NaN으로 표시

### <span style="color:RED">[참고]</span> 데이터 변경시 되도록 원본 데이터를 COPY 해서 사용할것!!
파이썬에서 Copy 메소드를 사용하지 않으면 주소값을 복사해서 사용기 때문에 원본 값을 변경 시키게 됩니다.    
따라서 원본 항목을 보전하면서 데이터를 보정하려면 copy 메소드를 사용 해주시기 바랍니다.

In [23]:
# copy() 함수를 이용해서 기존 Cust 데이터프레임을 새로운 cust_fix 데이터프레임으로 복사하기 
cust_fix = cust.copy()

In [24]:
# 새로 만든 cust_fix 데이터프레임 확인하기
cust_fix.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [99]:
# 이번에는 copy() 함수를 사용하지 않고 직접 대입해서  'test' 데이터프레임 만들어 보겠습니다. 
test = cust

In [100]:
# 새로 만든 test 데이터프레임 확인하기
# 내용은 같고 별차이를 모르겠네요. 

test.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [101]:
# 뭐가 다른지 알기 위해서, test 데이터프레임의 age 컬럼의 값들을 숫자 0 으로 변경해 보겠습니다.
test['age'] = 0

In [102]:
# test 데이터프레임의 age 컬럼의 값들을 확인해 보니 모두 숫자 0으로 나옵니다.
test.head()

  class  sex  age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F    0        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN    0        1    N    N    300.00   90.00  180.00           Y
2     E    F    0        1    N    N  16840.00 2526.00 6983.00           N
3     F    F    0        1    N    N  15544.73 2331.71 6750.47           N
4     D    M    0        1    N    N   4700.00    0.00 4502.00           N

In [103]:
# 위에서 test 데이터 변경 했으며, Cust 데이터프레임은 변경하지 않은 상태입니다.
# cust 데이터프레임을 확인해 보니, 
# cust 데이터프레임의 age 컬럼의 값들도 숫자 0으로 변경됨을 확인할수 있습니다. 

cust.head()

  class  sex  age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F    0        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN    0        1    N    N    300.00   90.00  180.00           Y
2     E    F    0        1    N    N  16840.00 2526.00 6983.00           N
3     F    F    0        1    N    N  15544.73 2331.71 6750.47           N
4     D    M    0        1    N    N   4700.00    0.00 4502.00           N

In [25]:
# 앞에서 Copy 함수로 변경한 Cust_fix 데이터 확인 보니
# 예전의 age 컬럼의 값들을 잘 보전하고 있습니다. 

cust_fix.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [88]:
# test = cust 처럼 직접 대입하여 사용하면, 주소로 복제되어 
# test 데이터프레임의 변경사항이 cust 데이터프레임에도 똑같이 반영됩니다.
# 그래서, 데이터 변경시에는 사전에 copy() 함수를 활용해서 복제해 두어 
# 변경 이전의 데이터프레임의 값들을 보전하면 좋습니다.
# 전의 cust 데이터프레임을 보관한 cust_fix 데이터프레임을 
# cust 데이터프레임에 다시 복제하도록 하겠습니다.

cust = cust_fix.copy()

In [78]:
# cust 데이터프레임의 age 컬럼의 값들이 정상적으로 보입니다. 
cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

### <b>결측치 채우기 </b>

사용자가 지정하는 단일값으로 채워서 결측치를 처리하는 방법입니다.

In [79]:
# 결측치 채우기 이전에 먼저, cust 데이터프레임에 NaN null 결측치가 있는지 확인해 봅니다.
# 확인해 보니, 1번 인덱스에 Class 컬럼, sex컬럼, age 컬럼에 NaN null 결측치가 보이네요.

cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [89]:
# 위와 같이 cust 데이터프레임 데이터를 조회해서 NaN null 있음을 육안으로 확인할수도 있고
# info() 함수를 사용해서 확인할수도 있습니다.
# info() 함수의 결과를 보니, 총라인건수가 9,930건인데 
# class 컬럼, sex컬럼, age컬럼에 NaN null 존재하여 각각 8,529건, 9,249건, 9,178건으로 9,930건이 
# 안되는것을 확인할수 있습니다.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8529 non-null   str
 1   sex          9249 non-null   str
 2   age          9178 non-null   float64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 775.9 KB

In [57]:
# 결측치 확인할수 있는 다른 방법은 isnull() 함수를 통해서 NaN null 확인 할수 있습니다.
# 각 value 값들이 null 이냐?고 물어 보는겁니다. 
# null이 맞으면 True, null이 아니면 False로 표현합니다. 

cust.isnull().head()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
0,False,False,False,False,False,False,False,False,False,False
1,True,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False

In [81]:
# isnull() 함수로 사용하니, 각 value 값들이 null 인지 , 아닌지 알수 있지만,
# 한눈에 안들어오므로, sum() 함수를 추가로 사용해서 컬럼별로 null 총합을 보도록 하겠습니다.
# class 컬럼에 1,401건의 null 값이 존재하고, sex 컬럼엔 681건, age 컬럼엔 752건의 null이 존재함을 알수 있습니다.

cust.isnull().sum()

class          1401
sex             681
age             752
service           0
stop              0
npay              0
avg_bill          0
A_bill            0
B_bill            0
termination       0
dtype: int64

In [90]:
# fillna 함수를 사용해서 cust 데이터프레임 전체에 대해서 
# NaN null값을 숫자 15로 변경해 보겠습니다. 
# 여기서는 테스트이므로 임의의 값으로 변경하지만, 
# 실무에서는 일괄적으로 변경시 데이터의 편향이 틀어질수 있음에 유의해 주시기 바랍니다. 
# (버전 오류로 현재 3.14 버전)

fill_dict = {
    col: '15' if col in ['class', 'sex'] else 15
    for col in cust.columns
}
cust = cust.fillna(fill_dict)

In [91]:
# 결측치를 숫자 15로 변경후 cust 데이터프레임을 확인해 보니
# 1번 인덱스에 존재하는 NaN도 15번 변경된것을 확인할수 있습니다.

cust.head()

  class sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C   F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1    15  15 15.00        1    N    N    300.00   90.00  180.00           Y
2     E   F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F   F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D   M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [92]:
# 앞에서 info 함수를 통해 확인해 보니, 
# 모든 컬럼의 라인개수가 9930건으로  결측치가 1개도 없음을 알수 있습니다.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        9930 non-null   str
 1   sex          9930 non-null   str
 2   age          9930 non-null   float64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 775.9 KB

In [54]:
# 다시 isnull() 함수를 사용해서 컬럼별 null 총합을 확인해 보겠습니다. 
# 모든 컬럼에는 null 갯수가 0으로 나와 null 없음을 확인할수 있습니다. 

cust.isnull().sum()

class          1401
sex             681
age             752
service           0
stop              0
npay              0
avg_bill          0
A_bill            0
B_bill            0
termination       0
dtype: int64

In [37]:
# 결측치 채우기로 데이터가 변경되어 , 
# 다음 실습을 위해 다시 결측치가 있는 이전의 데이터프레임으로 복사하겠습니다. 

cust = cust_fix.copy()

In [38]:
# cust 데이터프레임의 9927번 인덱스에 sex컬럼과 age 컬럼에 NaN null이 보이네요.
cust.tail()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
9925,C,F,15.00,1,N,Y,1296.10,194.41,643.10,N
9926,G,M,12.00,1,N,N,13799.67,2069.95,10605.93,N
9927,C,NaN,NaN,1,N,N,1396.20,1206.00,0.00,N
9928,C,F,40.00,0,N,N,3140.00,942.00,1884.00,Y
9929,C,F,59.00,1,N,N,2436.90,365.54,1839.90,N

fillna 함수의 Method 옵션을 사용해서, <br> 
데이터의 주변값으로 결측치를 채울수도 있습니다.

In [ ]:
# fillna 함수를 사용하여 결측치 채울때 특정값을 주었지만, 
# 이번에는 fillna 함수의 method 옵션을 'backfill' 주고 (구버전 1.x 이하, 현재 3.14 버전에는 이미 제거됨)
# 이번에는 bfill() 함수로,
# NaN 뒤에 있는 데이터값으로 결측치를 채워 보겠습니다.

# cust = cust.fillna(method='backfill') (구 버전)
cust = cust.bfill()

In [43]:
# cust 데이터프레임의 뒤 3개로 보니, 
# 기존 9927 인덱스의 sex컬럼과 age 컬럼의 NaN null이 
# 바로 뒤의 데이터값 'F'와 40.0으로 변경되었습니다.

cust.tail()

     class sex   age  service stop npay  avg_bill  A_bill   B_bill termination
9925     C   F 15.00        1    N    Y   1296.10  194.41   643.10           N
9926     G   M 12.00        1    N    N  13799.67 2069.95 10605.93           N
9927     C   F 40.00        1    N    N   1396.20 1206.00     0.00           N
9928     C   F 40.00        0    N    N   3140.00  942.00  1884.00           Y
9929     C   F 59.00        1    N    N   2436.90  365.54  1839.90           N

In [45]:
# 결측치 채우기로 데이터가 변경되어 , 
# 다음 실습을 위해 다시 결측치가 있는 이전의 데이터프레임으로 복사하겠습니다. 

cust = cust_fix.copy()

In [46]:
# cust 데이터프레임의 9927번 인덱스에 sex컬럼과 age 컬럼에 NaN null이 보이네요.
cust.tail()

,class,sex,age,service,stop,npay,avg_bill,A_bill,B_bill,termination
9925,C,F,15.00,1,N,Y,1296.10,194.41,643.10,N
9926,G,M,12.00,1,N,N,13799.67,2069.95,10605.93,N
9927,C,NaN,NaN,1,N,N,1396.20,1206.00,0.00,N
9928,C,F,40.00,0,N,N,3140.00,942.00,1884.00,Y
9929,C,F,59.00,1,N,N,2436.90,365.54,1839.90,N

In [47]:
# 이번에는 fillna 함수의 method 옵션을 'ffill' 주고  (구버전 1.x 이하, 현재 3.14 버전에는 이미 제거됨)
# NaN 앞에 있는 데이터값으로 결측치를 채워 보겠습니다. 

# cust = cust.fillna(method='ffill') (구 버전)
cust = cust.ffill()

In [48]:
# 적용된 결과를 확인해 보니
# 9927번 인덱스의 sex컬럼과 age컬럼에 Nan Null이 바로 앞의 데이터 'M'과 12.0 으로 
# 채워진것을 알수 있습니다.

cust.tail()

     class sex   age  service stop npay  avg_bill  A_bill   B_bill termination
9925     C   F 15.00        1    N    Y   1296.10  194.41   643.10           N
9926     G   M 12.00        1    N    N  13799.67 2069.95 10605.93           N
9927     C   M 12.00        1    N    N   1396.20 1206.00     0.00           N
9928     C   F 40.00        0    N    N   3140.00  942.00  1884.00           Y
9929     C   F 59.00        1    N    N   2436.90  365.54  1839.90           N

Replace 함수를 사용해도 결측치 채우기가 가능합니다.

In [94]:
# 1. 다시 결측치 실습을 위해 copy() 함수로 복사하고 
# 2. age 컬럼의 중앙값 확인 : 숫자 49.0으로 나오네요.

cust = cust_fix.copy()
cust[ 'age' ].median()

np.float64(49.0)

In [95]:
# 3. replace()함수로 NaN null결측치를 age컬럼의 중앙값으로 채워 보겠습니다.
cust['age'] = cust['age'].replace( np.nan, cust['age'].median() )

In [96]:
# 적용 결과를 확인해 보니, 1번 인덱스의 age 컬럼값이 숫자 49.0으로 변경되었습니다.
cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN 49.00        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

interpolate() 함수로 결측치 채우기     
선형방식은 값들을 같은 간격으로 처리하게된다.

In [105]:
# 1. 다시 결측치 실습을 위해 copy() 함수로 복사하고 
# 2. 결측치가 존재하는 앞과 뒤의 값을 보고 그 중간의 값으로 대체하는 
#    interpolate 함수을 사용하여 결측값을 채워 보겠습니다.

cust = cust_fix.copy()
numeric_cols = cust.select_dtypes(include=['int64', 'float64']).columns # 타입 에러를 위해 수정
cust[numeric_cols] = cust[numeric_cols].interpolate()

In [104]:
# interpolate 함수 적용 결과를 보니 
# 1번 인덱스의 age 컬럼의 NaN null값의 앞과 뒤의 값의 중간값
# 즉, 앞에는 28.0 이고 뒤에는 24.0 이므로, 여기의 중간값으로 26.0으로 
# 결측치를 채운것을 확인할수 있습니다. 

cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

### <b>결측치 제거하기</b>
결측치를 채우기로 처리하다보면 경우에 따라 값의 왜곡이 발생하는 경우가 있습니다.    
이때는 제거하기 기법을 사용하여 결측치를 처리하면 데이터의 정합성을 보존 할 수 있습니다.

* listwise 방식 : record의 항목 중 1개의 값이라도 NaN이면 해당 데이터 행 전체 제거
* pairwise 방식 : 모든 항목이 NaN인 데이터 행만 제거

In [106]:
# 결측치 실습을 위해 copy() 함수로 복사하겠습니다.
cust = cust_fix.copy()

In [107]:
# 결측치 제거하기 실습을 하기전에 , 다시 info 함수로 cust 데이터프레임 구성 보겠습니다.
# 전체 라인은 9930 개이고, class, sex, age 컬럼에 결측지 존재함을 알수 있습니다.

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8529 non-null   str
 1   sex          9249 non-null   str
 2   age          9178 non-null   float64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 775.9 KB

In [108]:
# listwise 방식 : 1개의 NaN이 존재하면 제거 하기
# dropna() 함수를 이용해서 1개의 NaN null이 있는 라인을 삭제해 보겠습니다.

cust = cust.dropna()

In [109]:
# 앞쪽의 dropna 함수를 적용하고 info 함수로 cust 데이터프레임을 확인해 보니
# 1개라도 NaN null 값이 있는 라인을 삭제하여 
# 전체 라인이 9930개에서 8228개로 줄어듬을 확인할수 있습니다.

cust.info()

<class 'pandas.DataFrame'>
Index: 8228 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8228 non-null   str
 1   sex          8228 non-null   str
 2   age          8228 non-null   float64
 3   service      8228 non-null   int64
 4   stop         8228 non-null   str
 5   npay         8228 non-null   str
 6   avg_bill     8228 non-null   float64
 7   A_bill       8228 non-null   float64
 8   B_bill       8228 non-null   float64
 9   termination  8228 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 707.1 KB

In [110]:
# pairwise 방식 : 전체 라인이 모든 컬럼의 값이 NaN null일 경우에 해당 라인 제거하기
# 1. 다시 결측치 실습을 위해 copy() 함수로 복사하고 
# 2. dropna() 함수의 how 옵션을 'all'로 설정하고 수행하면 
#    전체 라인이 NaN null로 되어 있는 라인를 제거하게 됩니다. 

cust = cust_fix.copy()
cust = cust.dropna(how='all')

In [111]:
# pairwise 방식으로 dropna 함수를 실행후 cust 데이터프레임 정보를 확인해 보니
# 기존 9930건와 똑같은 9930건으로 나옵니다. 
# 사실, 모든 컬럼의 값이 NaN null로 구성되어 있는 라인은 없습니다. 

cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class        8529 non-null   str
 1   sex          9249 non-null   str
 2   age          9178 non-null   float64
 3   service      9930 non-null   int64
 4   stop         9930 non-null   str
 5   npay         9930 non-null   str
 6   avg_bill     9930 non-null   float64
 7   A_bill       9930 non-null   float64
 8   B_bill       9930 non-null   float64
 9   termination  9930 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 775.9 KB

특정 열에 있는 NaN만 참고하여 결측치를 제거하려면 Subset 파라미터를 사용하면 됩니다.

In [115]:
# 특정열 안에서만 삭제하기
# 1. 다시 결측치 실습을 위해 copy() 함수로 복사하고 
# 2. cust 데이터프레임의 결측치 확인 보겠습니다. 

cust = cust_fix.copy()
cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [116]:
# 3. dropna() 함수의 subset 옵션을 사용해서 
#    'class' 특정컬럼에 대해서 NaN null 이 존재할 경우 해당 라인을 삭제해 보겠습니다.

cust = cust.dropna( subset=['class'] )

In [117]:
# class 컬럼에 NaN null 있으면 해당 라인은 삭제하게 되어 
# cust 데이터프레임의 1번 인덱스가 삭제된것을 확인할수 있습니다.

cust.head()

  class sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C   F 28.00        0    N    N   2640.00  792.00 1584.00           Y
2     E   F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F   F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D   M 18.00        1    N    N   4700.00    0.00 4502.00           N
5     C   F 78.00        1    N    N   1361.80 1174.00    0.00           N

### <b>결측치 처리한 데이터프레임을 파일로 저장하기</b>

In [118]:
# 기존에 복사해둔 cust_fix 데이터프레임을 복사합니다. 
# 이제는 뒤쪽 실습에서 사용할 데이터프레임을 만들고 저장하도록 하겠습니다. 

cust = cust_fix.copy()

In [119]:
# cust 데이터프레임 내용을 확인해 봅니다.
# 결측치 값들이 보입니다.

cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [120]:
# age 컬럼을 제외한 나머지 연속형 컬럼인 'service','avg_bill','A_bill','B_bill' 에 대해서만
# 결측치를 숫자 0으로 채우고 결과를 확인합니다.

cust[ ['service','avg_bill','A_bill','B_bill'] ] = cust[ ['service','avg_bill','A_bill','B_bill'] ].fillna(0)
cust.head()

  class  sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C    F 28.00        0    N    N   2640.00  792.00 1584.00           Y
1   NaN  NaN   NaN        1    N    N    300.00   90.00  180.00           Y
2     E    F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F    F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D    M 18.00        1    N    N   4700.00    0.00 4502.00           N

In [121]:
# 결측치가 있으면 해당 라인을 삭제합니다. 
# 위의 cust 데이터프레임과 dropna 결과후 cust 데이터프레임을 비교해 보니
# 1번 인덱스가 삭제된것을 알수 있습니다.

cust = cust.dropna()
cust.head()

  class sex   age  service stop npay  avg_bill  A_bill  B_bill termination
0     C   F 28.00        0    N    N   2640.00  792.00 1584.00           Y
2     E   F 24.00        1    N    N  16840.00 2526.00 6983.00           N
3     F   F 32.00        1    N    N  15544.73 2331.71 6750.47           N
4     D   M 18.00        1    N    N   4700.00    0.00 4502.00           N
5     C   F 78.00        1    N    N   1361.80 1174.00    0.00           N

In [122]:
# 인덱스 초기화하여 새롭게 인덱스 만들겠습니다. 
# 이빨빠진 기존 인덱스는 버리도록 drop=True 옵션을 주고, 
# inplace=True 옵션을 사용해서 해당 결과를 다시 cust 데이터프레임에 적용하겠습니다.

cust.reset_index(drop=True, inplace=True)
cust

     class sex   age  service stop npay  avg_bill  A_bill   B_bill termination
0        C   F 28.00        0    N    N   2640.00  792.00  1584.00           Y
1        E   F 24.00        1    N    N  16840.00 2526.00  6983.00           N
2        F   F 32.00        1    N    N  15544.73 2331.71  6750.47           N
3        D   M 18.00        1    N    N   4700.00    0.00  4502.00           N
4        C   F 78.00        1    N    N   1361.80 1174.00     0.00           N
...    ...  ..   ...      ...  ...  ...       ...     ...      ...         ...
8223     C   M 76.00        1    N    N   1860.00 1716.00     0.00           N
8224     C   F 15.00        1    N    Y   1296.10  194.41   643.10           N
8225     G   M 12.00        1    N    N  13799.67 2069.95 10605.93           N
8226     C   F 40.00        0    N    N   3140.00  942.00  1884.00           Y
8227     C   F 59.00        1    N    N   2436.90  365.54  1839.90           N

[8228 rows x 10 columns]

In [123]:
# 다음 실습을 위해, 현재의 cust 데이터프레임을 'cust_data.csv' 파일로 저장하겠습니다.

cust.to_csv('cust_data.csv', index=False)

In [124]:
# 모든 컬럼에 대해서 결측치 처리가 완료되었음을 확인
cust.isna().sum()

class          0
sex            0
age            0
service        0
stop           0
npay           0
avg_bill       0
A_bill         0
B_bill         0
termination    0
dtype: int64

<br>

<br>

# **[실습] 데이터 탐색과 결측치 처리 하기**

titanic.csv 데이터를 활용해서 아래와 같이 해 주세요.  
- 1. age를 제외한 모든 연속형 변수의 결측치를 0으로 결측치 처리하세요.
- 2. 나머지 결측치가 1개라도 있는 데이터는 제거하세요.
- 3. 모든 컬럼에 대해서 결측치 처리가 완료되었음을 확인하세요.

In [125]:
# 아래 딕셔너리를 활용하여 df 데이터프레임을 만드세요.
# 먼저, 판다스 임포트하기

import pandas as pd

In [126]:
# titanic.csv 파일 읽고 df 데이터프레임을 만들어 보자

df = pd.read_csv('../titanic.csv')

In [127]:
# df 데이터프레임의 앞쪽 5개 데이터 보기

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.92,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.05,NaN,S

In [ ]:
# df 데이터프레임의 뒤쪽 5개 데이터 보기

df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.00,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.00,0,0,370376,7.75,NaN,Q

In [128]:
# df 데이터프레임의 shape 정보 보기

df.shape

(891, 12)

In [129]:
# df 데이터프레임의 index 보기

df.index

RangeIndex(start=0, stop=891, step=1)

In [130]:
# df 데이터프레임의 columns 보기

df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [131]:
# df 데이터프레임의 columns에 대해서 마지막 2개의 컬럼만 뽑아 내기

df.columns[-2:]

Index(['Cabin', 'Embarked'], dtype='str')

In [132]:
# df 데이터프레임의 values 보기

df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], shape=(891, 12), dtype=object)

In [133]:
# df 데이터프레임의 info 보기

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [134]:
# df 데이터프레임의 통계정보 보기

df.describe()

       PassengerId  Survived  Pclass    Age  SibSp  Parch   Fare
count       891.00    891.00  891.00 714.00 891.00 891.00 891.00
mean        446.00      0.38    2.31  29.70   0.52   0.38  32.20
std         257.35      0.49    0.84  14.53   1.10   0.81  49.69
min           1.00      0.00    1.00   0.42   0.00   0.00   0.00
25%         223.50      0.00    2.00  20.12   0.00   0.00   7.91
50%         446.00      0.00    3.00  28.00   0.00   0.00  14.45
75%         668.50      1.00    3.00  38.00   1.00   0.00  31.00
max         891.00      1.00    3.00  80.00   8.00   6.00 512.33

In [135]:
# df 데이터프레임에서 'Survived', 'Pclass' 컬럼만 보기

df[ [ 'Survived', 'Pclass' ] ]

     Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

In [137]:
# df 데이터프레임에서 5번 인덱스의 행만 보기

df.loc[ 5 ]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                       8.46
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [138]:
# df 데이터프레임에서 5번~10번 인덱스의 행만 보기

df.loc[ 5 : 10,   ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.46,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.07,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.07,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.70,G6,S

In [139]:
# df 데이터프레임에서 5번~10번 인덱스와 'Survived' ~ 'Age' 컬럼만 가져오기

df.loc[ 5 : 10,  'Survived' : 'Age' ]

,Survived,Pclass,Name,Sex,Age
5,0,3,"Moran, Mr. James",male,NaN
6,0,1,"McCarthy, Mr. Timothy J",male,54.00
7,0,3,"Palsson, Master. Gosta Leonard",male,2.00
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00

In [140]:
# df 데이터프레임 앞 5개 내용 다시 보기 : Cabin 컬럼에 NaN null 보임.
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.92,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.05,NaN,S

In [141]:
# info 함수로 컬럼 타입과 null 확인 : Age, Cabin, Embarked 컬럼에 null 있음을 확인

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [142]:
# isnull() 함수 활용해서 컬럼별 null 합계 확인

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [143]:
# Cabin 컬럼에 891개중에 687개의 null 이 존재 --> 너무 많은 null존재해서 Cabin 컬럼 삭제

df.drop( 'Cabin', axis=1 , inplace=True)

In [144]:
# isnull() 함수 활용해서 컬럼별 null 합계 댜시 확인

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [145]:
# Cabin 컬럼 삭제된 데이터프레임 저장 

df_copy = df.copy()

In [146]:
# 결측치 재우기 
# Age 컬럼 : flaot64 , Cabin 컬럼과 Embarked 컬럼 : object 
# Age 컬럼은 평균값으로 채우기
# Cabin 컬럼과 Embarked 컬럼은 최빈값으로 채우기

# 1. Age 컬럼의 평균값
mean = df[ 'Age' ].mean()
mean

np.float64(29.69911764705882)

In [147]:
# 2. Age 컬럼의 결측치를 평균값으로 채우기
df[ 'Age' ] = df[ 'Age' ].fillna(mean)

In [148]:
# 3. Embarked 컬럼의 최빈값 확인하기
df[ 'Embarked' ].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [149]:
# 4. Embarked 컬럼의 결측치를 최빈값 'S' 으로 채우기
df[ 'Embarked' ] = df[ 'Embarked' ].fillna( 'S' )

In [150]:
# isnull() 함수 활용해서 컬럼별 null 합계 댜시 확인

df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [151]:
# 앞쪽에 보관한 df_copy 데이터프레임 복사하기 

df = df_copy.copy()

In [152]:
# isnull() 함수 활용해서 컬럼별 null 합계 댜시 확인

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [153]:
# null 값을 삭제 처리 : 801개 --> 712개로 행의 갯수 줄어듬

df = df.dropna()
df.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    str
 4   Sex          712 non-null    str
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    str
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 66.8 KB

<br>

<br>

# **정리**

데이터 전처리의 첫번째 파트을 살펴 보았습니다.    
- 데이터 탐색하기 : head(), tail(), info(), describe(), shape, columns, index, loc, iloc, sum(), mean() 등등
- 데이터 타입 변경하기 :astype()
- 결측치 : Missing Value로 데이터에 값이 없는 것을 의미. NA, Null, NaN으로 표시
- 결측치 처리하기 : isnull(), fillna(), dropna()
- 데이터 전처리 파트가 생각보다 쉽지 않고 알아야 될것이 너무 많기에 많은 연습 바랍니다. 겠습니다.