# **Pandas 이해 및 활용 - DataFrame 살펴보기**

- 데이터프레임에 대해서 실습하는 시간을 갖도록 하겠습니다. 
- 정말로, 데이터 탐색과 데이터전처리시에 너무나도 많이 사용하는 데이터프레임에 대해서 확실히 이해하는 시간을 되도록 하겠습니다. 
- 데이터프레임을 잘 다룰수 있다면, 그만큼 편하게 데이터 탐색과 전처리를 수행할수 있으며 시간도 많이 줄일수 있습니다.
- 이챕터에서는 DataFrame 정의, DataFrame 생성, DataFrame 내용 확인, DataFrame 조회하기
- 그리고, DataFrame boolean indexing , DataFrame  추가, 삭제에 대해서 배워 보도록 하겠습니다.

<br>

## __1. DataFrame이 뭔가요?__

>  - DataFrame은 2차원(col과 row을 가짐)테이블 데이터 구조를 가지는 자료형
>  - Data Analysis, Machine Learning에서 data 변형을 위해 가장 많이 사용
>  - **주의** : Series나 DataFrame은 대소문자가 구분되므로 Series, DataFrame으로 사용

In [2]:
# pandas import
import pandas as pd
import numpy as np

### <b>1-1. DataFrame 만들어 보기</b>

> Dictionary 형으로 생성

In [3]:
a1 = pd.DataFrame({"a" : [1,2,3], "b" : [4,5,6], "c" : [7,8,9]})
a1

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

>  List 형태로 데이터 프레임 생성

In [4]:
a2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], ["a","b","c"])
a2

   0  1  2
a  1  2  3
b  4  5  6
c  7  8  9

<br>

### <b>1-2. 파일을 읽어서 DataFrame생성하기</b>
> - pandas.read_csv 함수 사용
>  - 대부분의 업무에서는 분석하고자 하는 Datat가 존재할 것
>  - 이를 읽어 들이는 것부터 데이터 분석의 시작!
>  - 이번 실습에서 읽을 파일 : sc_cust_info_txn_v1.5.csv

In [27]:
# sc_cust_info_txn_v1.5.csv 데이터 파일을 읽어오기
cust = pd.read_csv('./sc_cust_info_txn_v1.5.csv')

In [28]:
# 데이터프레임 변수 cust 확인하기
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

- DataFrame 데이터 살펴보기
>DataFrame의 구조 (인덱스, 컬럼, Values 구성)
 - 인덱스(Index) : 행의 레이블에 대한 정보
 - 컬럼(Columns) : 열의 레이블에 대한 정보
 - 값(Values) : 데이터 값

In [49]:
# 데이터프레임 변수 cust의 인덱스, 컬럼, Values 확인해 보기
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

<br>

### <b>1-3. 데이터 살펴보기</b>
- head, tail 함수사용하기
> - 데이터 전체가 아닌, 일부(처음부터, 혹은 마지막부터)를 간단히 보기 위한 함수 (default: 5줄)
 - **head, tail을 왜 사용할까?**
   - 광대한 데이터를 다룰 수 있는 Pandas의 특성상 특정변수에 제대로 데이터가 들어갔는지 간략히 확인
   - 데이터 자료형의 확인
   - 각 레이블에 맞는 데이터 매칭 확인

In [50]:
# 그냥 head 함수 실행해 보기 : 앞부분 5 라인 출력
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N

In [51]:
# 앞부분 3개 라인 출력
cust.head(n=3)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0,792.0,1584.0,0.0,0.0,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0,90.0,180.0,0.0,0.0,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0,2526.0,6983.0,0.0,6981.0,N

In [52]:
#하위 5개 출력
cust.tail()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [53]:
#하위 3개 출력
cust.tail(n=3)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2,1206.000,0.0,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0,942.000,1884.0,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9,365.535,1839.9,0.0,1919.7999,N

- DataFrame 기본 함수로 살펴보기
  - **shape :** 속성 반환값은 튜플로 존재하며 row과 col의 개수를 튜플로 반환함(row,col순)
  - columns : 해당 DataFrame을 구성하는 컬럼명을 확인할 수 있음
  - **info**  : 데이터 타입, 각 아이템의 개수 등 출력
  - describe : 데이터 컬럼별 요약 통계량을 나타냄, 숫자형 데이터의 통계치 계산
            (count:데이터의 갯수 / mean:평균값 / std:표준편차 / min:최소값 / 4분위 수 / max:최대값) 
  - dtypes : 데이터 형태의 종류(Data Types)

In [54]:
# shape : 데이터를 파악하는데 중요함
cust.shape

(9930, 15)

In [55]:
# DataFrame의 columns들을 보여줌
cust.columns

Index(['base_ym', 'dpro_tgt_perd_val', 'cust_ctg_type', 'cust_class',
       'sex_type', 'age', 'efct_svc_count', 'dt_stop_yn', 'npay_yn',
       'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt', 'r3m_B_avg_arpu_amt',
       'r6m_A_avg_arpu_amt', 'r6m_B_avg_arpu_amt', 'termination_yn'],
      dtype='str')

In [56]:
# DataFrame의 index들을 보여줌
cust.index

RangeIndex(start=0, stop=9930, step=1)

In [57]:
# DataFrame의 index들을 보여줌
cust.index.values

array([   0,    1,    2, ..., 9927, 9928, 9929], shape=(9930,))

In [58]:
# DataFrame의 values들을 보여줌
cust.values

array([[202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
       [202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
       [202006, 20200630, 10001, ..., 0.0, 6981.0, 'N'],
       ...,
       [202006, 20200630, 10005, ..., 1212.0, 0.0, 'N'],
       [202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
       [202006, 20200630, 10001, ..., 0.0, 1919.7999, 'N']],
      shape=(9930, 15), dtype=object)

In [59]:
# 데이터 타입 및 각 아이템등의 정보를 보여줌
cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   str
 4   sex_type            9930 non-null   str
 5   age                 9930 non-null   str
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   str
 8   npay_yn             9930 non-null   str
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   str
dtypes: float64(5), int64(4), str(6)
memory usage: 1.1 MB

In [60]:
# DataFrame의 기본적인 통계정보를 보여줌
# 개수, 평균, 표준편차, 최소값, 1분위, 중간값, 3분위, 최대값 제공

cust.describe()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
count,9930.0,9930.0,9930.000000,9930.000000,9.930000e+03,9.930000e+03,9.930000e+03,9.930000e+03,9930.000000
mean,202006.0,20200630.0,10001.372810,1.520040,1.181774e+04,1.897536e+03,6.395259e+03,8.496206e+02,4624.897630
std,0.0,0.0,1.605016,15.404037,1.397822e+05,1.235342e+04,8.346138e+04,1.235124e+04,4561.049131
min,202006.0,20200630.0,10001.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,202006.0,20200630.0,10001.000000,1.000000,3.624503e+03,3.240000e+02,1.260000e+03,0.000000e+00,0.000000
50%,202006.0,20200630.0,10001.000000,1.000000,8.284467e+03,1.593307e+03,4.768617e+03,0.000000e+00,3959.316700
75%,202006.0,20200630.0,10001.000000,1.000000,1.372000e+04,2.308360e+03,7.982000e+03,1.006125e+03,7741.006900
max,202006.0,20200630.0,10010.000000,905.000000,1.281568e+07,1.188998e+06,7.689409e+06,1.208498e+06,64947.092000

In [61]:
# DataFrame의 데이터 종류
cust.dtypes

base_ym                 int64
dpro_tgt_perd_val       int64
cust_ctg_type           int64
cust_class                str
sex_type                  str
age                       str
efct_svc_count          int64
dt_stop_yn                str
npay_yn                   str
r3m_avg_bill_amt      float64
r3m_A_avg_arpu_amt    float64
r3m_B_avg_arpu_amt    float64
r6m_A_avg_arpu_amt    float64
r6m_B_avg_arpu_amt    float64
termination_yn            str
dtype: object

<br>

<br>

## __2. Data 조회하기__
DataFrame에서 data를 __조회, 수정__해보고 이를 이해해본다.

<br>

### <b>1-1. 데이터 추출하기</b>

#### <b>1) column 선택하기</b>

> - 기본적으로 [ ]는 column을 추출 : 특정한 col을기준으로 모델링을 하고자 하는 경우
> - 컬럼 인덱스일 경우 인덱스의 리스트 사용 가능
>   - 리스트를 전달할 경우 결과는 Dataframe
>   - 하나의 컬럼명을 전달할 경우 결과는 Series

#### <b>2) 하나의 컬럼 선택하기</b>

> - Series 형태로 가지고 올 수도, DataFrame형태로 가지고 올 수 있음

In [62]:
cust.cust_class = cust['cust_class']

In [63]:
cust.cust_class

0       C
1       _
2       E
3       F
4       D
       ..
9925    C
9926    G
9927    C
9928    C
9929    C
Name: cust_class, Length: 9930, dtype: str

In [64]:
# cf : series 형태로 가지고 오기(hcust.cust_class = cust['cust_class'])
cust['cust_class']

0       C
1       _
2       E
3       F
4       D
       ..
9925    C
9926    G
9927    C
9928    C
9929    C
Name: cust_class, Length: 9930, dtype: str

In [65]:
# cf : Dataframe형태로 가지고 오기
cust[['cust_class']]

     cust_class
0             C
1             _
2             E
3             F
4             D
...         ...
9925          C
9926          G
9927          C
9928          C
9929          C

[9930 rows x 1 columns]

#### <b>3) 복수의 컬럼 선택하기</b>

In [66]:
# 여러개의 요소들을 선택시 리스틀 사용하여 표시하면 된다.
# 'cust_class' , 'age' 'r3m_avg_bill_amt' 3개의 컬럼들을 리스트에 넣어 선택하면 된다. 

cust[['cust_class', 'age', 'r3m_avg_bill_amt']]

     cust_class age  r3m_avg_bill_amt
0             C  28         2640.0000
1             _   _          300.0000
2             E  24        16840.0000
3             F  32        15544.7334
4             D  18         4700.0000
...         ...  ..               ...
9925          C  15         1296.0999
9926          G  12        13799.6666
9927          C   _         1396.2000
9928          C  40         3140.0000
9929          C  59         2436.9000

[9930 rows x 3 columns]

#### <b>4) DataFrame slicing</b>

>- 특정 **행 범위**를 가지고 오고 싶다면 [ ]를 사용
>- DataFrame의 경우 기본적으로 [ ] 연산자가 **column 선택**에 사용되지만 **slicing은 row 레벨**로 지원

In [67]:
# 7,8,9행을 가지고 옴 (인덱스 기준)
cust[7:10]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
7,202006,20200630,10001,D,F,65,1,N,N,4953.9334,987.0000,2700.3999,0.0000,2689.1,N
8,202006,20200630,10001,D,M,60,1,N,N,5503.0000,2093.0001,0.0000,1981.8999,0.0,N
9,202006,20200630,10001,C,F,67,1,N,N,1349.7000,1227.0000,0.0000,985.5000,0.0,N

> **[주의] 데이터프레임에 대해 인덱스 접근시 에러 발생**     
> 기본적으로 데이터프레임은 인덱스 접근시 컬럼명 접근으로 설계되어 인덱스 번호 0 번, 1번은 컬럼명에 없으므로 에러가 발생합니다. 
>

In [68]:
# cust 데이터프레임의 7번 인덱스 접근 : 키 에러 발생
cust[ 7 ]

KeyError: 7

In [ ]:
# 그래서 1개의 인덱스로 접근시 컬럼명을 사용해야 에러가 안남
# 아래와 같이 인덱스를 base_ym 컬럼명으로 사용하면 됨. 
# 화면 결과는 인덱스와 값으로 구성된 Series 임.

cust[ 'base_ym' ]

0       202006
1       202006
2       202006
3       202006
4       202006
         ...
9925    202006
9926    202006
9927    202006
9928    202006
9929    202006
Name: base_ym, Length: 9930, dtype: int64

#### <b>5) row 선택하기</b>

 - DataFrame에서는 기본적으로 **[ ]을 사용하여 column을 선택**
 > __row 선택(두가지 방법이 존재)__
 > - **loc** : Dataframe에 존재하는 **인덱스를 그대로 사용** (인덱스 기준으로 행 데이터 읽기)
 > - **iloc** : Datafrmae에 존재하는 인덱스 상관없이 **0 based index로 사용** (행 번호 기준으로 행 데이터 읽기)
 > - 이 두 함수는 ,를 사용하여 column 선택도 가능

In [ ]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   object
 4   sex_type            9930 non-null   object
 5   age                 9930 non-null   object
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   object
 8   npay_yn             9930 non-null   object
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   object
dtypes: float64(5), int64(4), object(6)
memory usage: 1.1+ MB

In [ ]:
# arange함수는 10부터 19에서 끝나도록 간격을 1로 반환한다.
cp=np.arange(10,20)
cp

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# 9930 라인이 있으며 인덱스는 0부터 9929까지 나오게 됨
cust.index

RangeIndex(start=0, stop=9930, step=1)

In [ ]:
#index를 100부터 달아주기 
cust.index = np.arange(100, 10030)
cust.index

Index([  100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
       ...
       10020, 10021, 10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029],
      dtype='int32', length=9930)

In [ ]:
# cust 데이터프레임의 앞부분 확인 : 인덱스가 100부터 시작 확인
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N

In [ ]:
# cust 데이터프레임의 뒤부분 확인 : 인덱스가 10029로 끝나는것 확인
cust.tail()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
10025,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
10026,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
10027,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
10028,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
10029,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [ ]:
#l oc 함수를 이용해서 한개의 row만 가지고 오기 
# 아래 보이는 형식은 시리즈이며, 인덱스와 값으로 구성된다. 
cust.loc[ 10028 ]

base_ym                 202006
dpro_tgt_perd_val     20200630
cust_ctg_type            10001
cust_class                   C
sex_type                     F
age                         40
efct_svc_count               0
dt_stop_yn                   N
npay_yn                      N
r3m_avg_bill_amt        3140.0
r3m_A_avg_arpu_amt       942.0
r3m_B_avg_arpu_amt      1884.0
r6m_A_avg_arpu_amt         0.0
r6m_B_avg_arpu_amt         0.0
termination_yn               Y
Name: 10028, dtype: object

In [ ]:
# 다시 loc 함수를 이용해서 한개의 row만 가지고 오기 
# 리스트에 인덱스 번호를 넣어 편하기 보자 : 1개 라인이지만, 화면에 보이는 형식은 데이터프레임이다.
cust.loc[ [ 10028 ] ]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
10028,202006,20200630,10001,C,F,40,0,N,N,3140.0,942.0,1884.0,0.0,0.0,Y

In [ ]:
# 이번에는 여러개의 row 가져와 보기 
cust.loc[[102, 202, 302]]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
102,202006,20200630,10001,E,F,24,1,N,N,16840.00000,2526.0000,6983.0,0.0,6981.00,N
202,202006,20200630,10010,_,_,_,1,N,N,22362.93330,2082.0000,9410.0,0.0,9408.00,N
302,202006,20200630,10001,G,M,52,1,N,Y,17769.50989,1506.9999,14647.1,0.0,14744.95,N

In [ ]:
# 이번에는 iloc 함수를 사용하여 loc 함수와 비교해 보자. 
# iloc는 인덱스 번호와 다르게 내부적으로 첫번위치를 0으로 계산해서 쭉 나아간다고 생각하자.
cust.iloc[[2, 102, 202]]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
102,202006,20200630,10001,E,F,24,1,N,N,16840.00000,2526.0000,6983.0,0.0,6981.00,N
202,202006,20200630,10010,_,_,_,1,N,N,22362.93330,2082.0000,9410.0,0.0,9408.00,N
302,202006,20200630,10001,G,M,52,1,N,Y,17769.50989,1506.9999,14647.1,0.0,14744.95,N

- row, column 동시에 선택하기
 > loc, iloc 속성을 이용할 때, 콤마를 이용하여 row와 col 다 명시 가능

In [ ]:
# loc 함수를 사용하여 cust 데이터프레임에서 102번째 인덱스의 'age' 컬럼의 값만 가져오기 
cust.loc[ 102, 'age' ]

'24'

In [ ]:
# loc 함수를 사용하여 100, 200, 300 대상으로 cust_class, sex_type, age, r3m_avg_bill_amt, r3m_A_avg_arpu_amt  col 가지고 오기
# 여러개의 요소를 선택하려면 [] 리스트를 사용해야 함을 기억해 주세요.

cust.loc[[100, 200, 300], ['cust_class', 'sex_type', 'age', 'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]   # row, col

    cust_class sex_type age  r3m_avg_bill_amt  r3m_A_avg_arpu_amt
100          C        F  28        2640.00000            792.0000
200          E        M  61        9526.77000           1878.9000
300          D        M  84       11622.37472           2716.7952

In [ ]:
# 같은 형태로 iloc사용하여 
# 100, 200, 300 대상으로 cust_class, sex_type, age, r3m_avg_bill_amt, r3m_A_avg_arpu_amt  col 가지고 오기
# iloc 함수의 경우, 인덱스와 컬럼들의 절대적 위치로 표현하는걸 알수 있다.

cust.iloc[[0, 100, 200], [3, 4, 5, 9, 10]]

    cust_class sex_type age  r3m_avg_bill_amt  r3m_A_avg_arpu_amt
100          C        F  28        2640.00000            792.0000
200          E        M  61        9526.77000           1878.9000
300          D        M  84       11622.37472           2716.7952

#### __6) boolean indexing으로 row 선택하기__

 - 해당 조건에 맞는 row만 선택
 - 조건을 명시하고 조건을 명시한 형태로 inedxing 하여 가지고 옴
 - 2개 이상의 조건을 묶을때 AND나 OR을 사용할수 있으며, boolean indexing에서는 AND는 & 로, OR은 | 로 사용하오니 기억해 주시기 바랍니다.

 - ex: 남자이면서 3개월 평균 청구 금액이 50000 이상이면서 100000 미만인 사람만 가지고오기

In [ ]:
# 조건 : 남자이면서 3개월 평균 청구 금액이 50000 이상이면서 100000 미만인 사람만 가지고오기
# 조건 분해 
# 1. 남자
# 2. 개월 평균 청구 금액이 50000 이상이면서 100000 미만

In [ ]:
# 첫번째 조건 : 남자 > 확인해 보자. 
# 먼저, 남녀 값을 가지고 있는 성별 'sex_type' 컬럼의 내용을 확인해 보자. 
cust['sex_type'].head()

100    F
101    _
102    F
103    F
104    M
Name: sex_type, dtype: object

In [ ]:
# 성별 sex_type 컬럼의 값이 'M' 인 조건문 만들어 보자.
# 시리즈 형태로 보이며, 조건에 일치하면 True, 조건에 일치하지 않으면 False 구성되는것 확인

cust['sex_type'] == 'M'

100      False
101      False
102      False
103      False
104       True
         ...
10025    False
10026     True
10027    False
10028    False
10029    False
Name: sex_type, Length: 9930, dtype: bool

In [ ]:
# 그럼, 성별 sex_type 컬럼의 값이 'M' 남자인 데이터만 뽑아 보자.
# cust 데이터프레임에 조건문을 넣어주면 끝.
# 결과 출력을 보면 성별 sex_type 컬럼의 값이 'M' 남자만 있는것을 확인할수 있다.
# 이런식으로 조건을 사용하여 우리가 원하는 Raw들을 추출할수 있다. 

cust[  cust['sex_type'] == 'M'  ]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
104,202006,20200630,10001,D,M,18,1,N,N,4700.00000,0.00000,4502.0000,0.0000,4507.7000,N
106,202006,20200630,10001,D,M,22,1,N,N,13562.80000,2222.00010,3673.0000,0.0000,3671.0000,N
108,202006,20200630,10001,D,M,60,1,N,N,5503.00000,2093.00010,0.0000,1981.8999,0.0000,N
111,202006,20200630,10001,F,M,59,1,N,N,11472.33340,348.80010,8910.1334,0.0000,8908.0666,N
115,202006,20200630,10001,C,M,87,1,N,Y,2774.93326,2522.66660,0.0000,1233.9999,0.0000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10020,202006,20200630,10001,D,M,46,0,N,N,6920.00000,2076.00000,4152.0000,0.0000,0.0000,Y
10021,202006,20200630,10001,D,M,54,1,N,Y,5198.06660,0.00000,4760.8666,0.0000,4749.3000,N
10022,202006,20200630,10001,E,M,65,4,N,N,9115.13340,3209.60000,0.0000,3523.7334,0.0000,N
10023,202006,20200630,10001,C,M,76,1,N,N,1860.00000,1716.00000,0.0000,1722.0000,0.0000,N
10026,202006,20200630,10001,G,M,12,1,N,N,13799.66660,2069.94999,10605.9266,0.0000,10603.9266,N

In [ ]:
# 위에서 우리가 찾을 조건 : "남자이면서 3개월 평균 청구 금액이 50000 이상이면서 100000 미만인 사람만" 가지고오기
# 조건1. 남자 
# 조건2. 3개월 평균 청구 금액이 50000 이상이면서 100000 미만
# 위에서 첫번째 조건 cust['sex_type']=='M' 확인했고 두번째 조건을 만들어 보자.
# 3개월 평균 청구 금액에 해당되는 컬럼명은 'r3m_avg_bill_amt' 이며 해당 컬럼을 가지고 조건문을 만들어 보자.
# 주의 사항은 조건문은 소괄호()로 묶어 주면 에러가 나지 않아, 되도록이면 소괄호로 묶어주는게 좋겠다. 
# 그리고, 3개월 평균 청구 금액이 50000 이상이면서 100000 미만이기에 중간의 & AND 논리연산자를 넣어 두개의 조건을 연결해 준다.
# 결과 출력을 보면 , 조건에 맞는것은  True 로 출력되고, 맞지 않는것은 False 로 출력된다.(시리즈 형태) 

( cust[ 'r3m_avg_bill_amt' ] >= 50000 ) & ( cust['r3m_avg_bill_amt'] < 100000 )

100      False
101      False
102      False
103      False
104      False
         ...
10025    False
10026    False
10027    False
10028    False
10029    False
Name: r3m_avg_bill_amt, Length: 9930, dtype: bool

In [ ]:
# 위에서 만든 남자 조건과 3개월 평균 청구 금액이 50000 이상이면서 100000 미만 조건을 cust 데이터프레임에 넣어주면 된다.

cust[ ( cust['sex_type']=='M' ) & ( cust['r3m_avg_bill_amt']>=50000 ) & ( cust['r3m_avg_bill_amt']< 100000 ) ]

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
472,202006,20200630,10001,F,M,28,1,N,N,65113.66670,1310.400000,20083.5033,0.0000,19426.1983,N
1149,202006,20200630,10001,D,M,20,2,N,N,80335.67685,69136.100100,3896.3334,0.0000,3727.6666,N
1464,202006,20200630,10001,_,M,45,1,N,Y,54865.70000,2321.866600,8744.9382,0.0000,8774.7162,N
1893,202006,20200630,10001,G,M,48,1,N,N,64804.34037,47599.450100,11313.5866,0.0000,11351.4984,N
2127,202006,20200630,10001,G,M,47,1,N,Y,55368.98422,37432.266600,12903.1736,0.0000,12901.1736,N
2197,202006,20200630,10001,G,M,35,1,N,N,97205.00000,1820.799900,17491.6473,0.0000,12377.2057,N
2477,202006,20200630,10001,G,M,25,1,N,Y,68290.60000,1296.000000,40974.3600,0.0000,0.0000,Y
2492,202006,20200630,10001,G,M,23,1,N,Y,53565.53330,2751.000000,18515.6012,0.0000,17212.4013,N
2668,202006,20200630,10001,G,M,29,1,N,Y,68811.53330,2783.800000,8759.7534,0.0000,10098.9034,N
2704,202006,20200630,10001,G,M,43,1,N,Y,56557.13330,2041.599900,18895.0078,0.0000,14743.8312,N
3241,202006,20200630,10001,G,M,26,1,N,N,77217.60000,23165.280000,46330.5600,0.0000,0.0000,Y
4160,202006,20200630,10001,H,M,44,3,N,Y,77490.26670,11623.540010,30360.6833,0.0000,30402.5750,N
4591,202006,20200630,10001,F,M,30,1,N,Y,73000.36670,10950.055010,18250.7000,0.0000,19560.3833,N
5859,202006,20200630,10001,G,M,56,1,N,Y,76741.06670,11511.160010,15445.2566,0.0000,15442.4874,N
6146,202006,20200630,10001,G,M,46,1,N,Y,55711.96670,8356.795005,10560.5666,0.0000,9302.1500,N
7372,202006,20200630,10001,H,M,62,1,N,Y,96136.10000,14420.415000,20996.9894,0.0000,20995.9894,N
8994,202006,20200630,10001,G,M,31,1,N,Y,62542.13330,9381.319995,13674.5906,0.0000,14418.1732,N
9177,202006,20200630,10001,G,M,23,1,N,Y,68571.96670,10285.795010,19643.3666,0.0000,10061.7083,N
9542,202006,20200630,10001,G,M,19,1,N,N,53123.46670,7968.520005,6561.2666,0.0000,7037.9334,N
9591,202006,20200630,10001,F,M,39,1,N,N,51111.56670,7666.735005,4570.9200,0.0000,0.0000,N
9647,202006,20200630,10001,H,M,52,4,Y,Y,64569.80000,9685.470000,10662.3527,0.0000,13548.9108,N
9733,202006,20200630,10001,G,M,45,3,N,N,64404.96670,2999.700000,2582.9559,2017.6668,7261.2774,N

In [ ]:
# 조건문이 너무 길어지거나 복잡해지면...아래와 같은 방식으로 해도 무방함
# 남자이면서 
sex = ( cust['sex_type']=='M' )
# 3개월 평균 청구 금액이 50000 이상이면서 100000 미만
bill = (cust['r3m_avg_bill_amt']>=50000) & (cust['r3m_avg_bill_amt']< 100000)

cust[ sex & bill ].head(3)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
472,202006,20200630,10001,F,M,28,1,N,N,65113.66670,1310.4000,20083.5033,0.0,19426.1983,N
1149,202006,20200630,10001,D,M,20,2,N,N,80335.67685,69136.1001,3896.3334,0.0,3727.6666,N
1464,202006,20200630,10001,_,M,45,1,N,Y,54865.70000,2321.8666,8744.9382,0.0,8774.7162,N

<br>

<br>

### <b>1-2. 데이터 추가/삭제하기</b>

#### <b>1) 새 column 추가하기</b>

>- 데이터 전처리 과정에서 빈번하게 발생하는 것
>- insert 함수 사용하여 원하는 위치에 추가하기

In [ ]:
# r3m_avg_bill_amt 두배로 새로운 col만들기
cust['r3m_avg_bill_amt2'] = cust['r3m_avg_bill_amt'] * 2
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y,5280.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y,600.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N,33680.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N,31089.4668
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N,9400.0000

In [ ]:
# 기존에 col을 연산하여 새로운 데이터 생성
cust['r3m_avg_bill_amt3'] = cust['r3m_avg_bill_amt2'] + cust['r3m_avg_bill_amt']
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2,r3m_avg_bill_amt3
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y,5280.0000,7920.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y,600.0000,900.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N,33680.0000,50520.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N,31089.4668,46634.2002
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N,9400.0000,14100.0000

#### __2) column 삭제하기__

>- drop 함수 사용하여 삭제
>- axis는 삭제를 가로(행)기준으로 할 것인지, 세로(열)기준으로 할 것인지 명시하는 'drop()'메소드의 파라미터임 
>- 리스트를 사용하면 멀티플 col 삭제 가능

In [ ]:
# axis : dataframe은 차원이 존재 함으로 항상 0과 1이 존재 (0은 행레벨, 1을 열 레벨)
# drop 함수 수행시 화면에 출력되며, 해당 내용은 cust 데이터프레임에 저장된게 아니므로 주의하자.

cust.drop('r3m_avg_bill_amt3', axis=1)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y,5280.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y,600.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N,33680.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N,31089.4668
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N,9400.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N,2592.1998
10026,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N,27599.3332
10027,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N,2792.4000
10028,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y,6280.0000
10029,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N,4873.8000

In [ ]:
#원본 데이터를 열어 보면 원본 데이터는 안 지워진 상태
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2,r3m_avg_bill_amt3
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y,5280.0000,7920.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y,600.0000,900.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N,33680.0000,50520.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N,31089.4668,46634.2002
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N,9400.0000,14100.0000

In [ ]:
# 원본 데이터를 지우고자 한다면... 
# 방법1 : 데이터를 지우고 다른 데이터 프레임에 저장
cust1 = cust.drop('r3m_avg_bill_amt3', axis=1)
cust1.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y,5280.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y,600.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N,33680.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N,31089.4668
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N,9400.0000

In [ ]:
# 원본 자체를 지우고자 한다면...
# 방법 2 : inplace 파라미터를 할용 True인 경우 원본데이터에 수행
cust.drop('r3m_avg_bill_amt3', axis=1, inplace=True)

In [ ]:
# 원본확인
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y,5280.0000
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y,600.0000
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N,33680.0000
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N,31089.4668
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N,9400.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N,2592.1998
10026,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N,27599.3332
10027,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N,2792.4000
10028,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y,6280.0000
10029,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N,4873.8000

In [ ]:
# 추가로 drop 함수를 이용해서 컬럼이 아니라 행을 삭제할수 있습니다.
# 이때 axis=0 을 사용하고 우리가 삭제하고자 하는 인덱스 번호를 주시면 됩니다.
# cust 데이터프레임에서 100,101,102 행을 삭제해 보겠습니다. 

cust.drop( [100, 101, 102] , axis=0 )

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn,r3m_avg_bill_amt2
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N,31089.4668
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N,9400.0000
105,202006,20200630,10001,C,F,78,1,N,N,1361.7999,1173.999900,0.0000,1123.5,0.0000,N,2723.5998
106,202006,20200630,10001,D,M,22,1,N,N,13562.8000,2222.000100,3673.0000,0.0,3671.0000,N,27125.6000
107,202006,20200630,10001,D,F,65,1,N,N,4953.9334,987.000000,2700.3999,0.0,2689.1000,N,9907.8668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N,2592.1998
10026,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N,27599.3332
10027,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N,2792.4000
10028,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y,6280.0000
10029,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N,4873.8000

<br>

<br>

# **[실습] 데이터프레임 살펴보기**

1. 아래 딕셔너리를 활용하여 df 데이터프레임을 만드세요.

<pre>
data = {
    '이름' : ['루피', '조로', '상디', '나미', '우솝', '쵸파', '로빈', '프랑키'],
    '고향' : ['Eastblue','Northblue','Northblue', 'Eastblue', 'Grandline', 'Grandline', 'OHARA', 'Waterseven'],
    '키' : [174, 181, 180, 170, 173, 90, 188, 240],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    '기술' : ['레드호크', '아수라', '디아블잠브', '', '', '', '풀루르', '라디컬 빔']   
}

</pre>

In [ ]:
# 아래 딕셔너리를 활용하여 df 데이터프레임을 만드세요.
# 먼저, 판다스 임포트하기

import pandas as pd

In [ ]:
# 아래 딕셔너리를 활용하여 df 데이터프레임을 만들고 내용 조회하기

data = {
    '이름' : ['루피', '조로', '상디', '나미', '우솝', '쵸파', '로빈', '프랑키'],
    '고향' : ['Eastblue','Northblue','Northblue', 'Eastblue', 'Grandline', 'Grandline', 'OHARA', 'Waterseven'],
    '키' : [174, 181, 180, 170, 173, 90, 188, 240],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    '기술' : ['레드호크', '아수라', '디아블잠브', '', '', '', '풀루르', '라디컬 빔']   
}

df = pd.DataFrame( data )   
df

    이름          고향    키   국어   영어   수학  과학  사회     기술
0   루피    Eastblue  174   90   85  100  95  85   레드호크
1   조로   Northblue  181   40   35   50  55  25    아수라
2   상디   Northblue  180   80   75   70  80  75  디아블잠브
3   나미    Eastblue  170   40   60   70  75  80
4   우솝   Grandline  173   15   20   10  35  10
5   쵸파   Grandline   90   80  100   95  85  80
6   로빈       OHARA  188   55   65   45  40  35    풀루르
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔

In [ ]:
# df 데이터프레임의 앞쪽 5개 데이터 보기

df.head()

   이름         고향    키  국어  영어   수학  과학  사회     기술
0  루피   Eastblue  174  90  85  100  95  85   레드호크
1  조로  Northblue  181  40  35   50  55  25    아수라
2  상디  Northblue  180  80  75   70  80  75  디아블잠브
3  나미   Eastblue  170  40  60   70  75  80
4  우솝  Grandline  173  15  20   10  35  10

In [ ]:
# df 데이터프레임의 뒤쪽 5개 데이터 보기

df.tail()

    이름          고향    키   국어   영어  수학  과학  사회     기술
3   나미    Eastblue  170   40   60  70  75  80
4   우솝   Grandline  173   15   20  10  35  10
5   쵸파   Grandline   90   80  100  95  85  80
6   로빈       OHARA  188   55   65  45  40  35    풀루르
7  프랑키  Waterseven  240  100   85  90  95  95  라디컬 빔

In [ ]:
# df 데이터프레임의 shape 정보 보기

df.shape

(8, 9)

In [ ]:
# df 데이터프레임의 index 보기

df.index
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
# df 데이터프레임의 columns 보기

df.columns

Index(['이름', '고향', '키', '국어', '영어', '수학', '과학', '사회', '기술'], dtype='object')

In [ ]:
# df 데이터프레임의 columns에 대해서 마지막 2개의 컬럼만 뽑아 내기

df.columns[-2:]

Index(['사회', '기술'], dtype='object')

In [ ]:
# df 데이터프레임의 values 보기

df.values

array([['루피', 'Eastblue', 174, 90, 85, 100, 95, 85, '레드호크'],
       ['조로', 'Northblue', 181, 40, 35, 50, 55, 25, '아수라'],
       ['상디', 'Northblue', 180, 80, 75, 70, 80, 75, '디아블잠브'],
       ['나미', 'Eastblue', 170, 40, 60, 70, 75, 80, ''],
       ['우솝', 'Grandline', 173, 15, 20, 10, 35, 10, ''],
       ['쵸파', 'Grandline', 90, 80, 100, 95, 85, 80, ''],
       ['로빈', 'OHARA', 188, 55, 65, 45, 40, 35, '풀루르'],
       ['프랑키', 'Waterseven', 240, 100, 85, 90, 95, 95, '라디컬 빔']],
      dtype=object)

In [ ]:
# df 데이터프레임의 info 보기

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      object
 1   고향      8 non-null      object
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   기술      8 non-null      object
dtypes: int64(6), object(3)
memory usage: 708.0+ bytes

In [ ]:
# df 데이터프레임의 통계정보 보기

df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   174.500000   62.500000   65.625000   66.250000  70.000000  60.625000
std     40.897083   29.519969   26.917533   30.325614  23.754699  32.120032
min     90.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    172.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    177.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    182.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    240.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [ ]:
# df 데이터프레임에서 키컬럼과 영어컬럼만 보기

df[ [ '키' , '영어' ] ]

     키   영어
0  174   85
1  181   35
2  180   75
3  170   60
4  173   20
5   90  100
6  188   65
7  240   85

In [ ]:
# df 데이터프레임에서 5번 인덱스의 '국어' 컬럼의 값 확인하기

df.loc[ 5,  '국어' ]

80

In [ ]:
# df 데이터프레임 내용 다시 확인하기

df

    이름          고향    키   국어   영어   수학  과학  사회     기술
0   루피    Eastblue  174   90   85  100  95  85   레드호크
1   조로   Northblue  181   40   35   50  55  25    아수라
2   상디   Northblue  180   80   75   70  80  75  디아블잠브
3   나미    Eastblue  170   40   60   70  75  80
4   우솝   Grandline  173   15   20   10  35  10
5   쵸파   Grandline   90   80  100   95  85  80
6   로빈       OHARA  188   55   65   45  40  35    풀루르
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔

In [ ]:
# boolean indexing을 활용해서 국어 점수가 80 이상인 데이터만 뽑아 보기
# 먼저, 국어점수 80 점 이상인 라인만 추출하기

df[ '국어' ] >= 80

0     True
1    False
2     True
3    False
4    False
5     True
6    False
7     True
Name: 국어, dtype: bool

In [ ]:
# boolean indexing을 활용해서 국어 점수가 80 이상인 데이터만 뽑아 보기
# 국어점수 80 점 이상인 라인을 cond 저장하고 df 데이터프레임에서 조회하기

cond = ( df[ '국어' ] >= 80 )
df[ cond ]

    이름          고향    키   국어   영어   수학  과학  사회     기술
0   루피    Eastblue  174   90   85  100  95  85   레드호크
2   상디   Northblue  180   80   75   70  80  75  디아블잠브
5   쵸파   Grandline   90   80  100   95  85  80
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔

In [ ]:
# boolean indexing을 활용해서 국어 점수가 80 이상이고 수학 점수가 90 이상인 데이터만 뽑아 보기
# 국어점수 80 점 이상에 대한 boolean indexing  AND  수학점수 90 점 이상에 대한 boolean indexing

( df[ '국어' ] >= 80 ) & ( df[ '수학' ] >= 90 )

0     True
1    False
2    False
3    False
4    False
5     True
6    False
7     True
dtype: bool

In [ ]:
# boolean indexing을 활용해서 국어 점수가 80 이상이고 수학 점수가 90 이상인 데이터만 뽑아 보기
# 국어점수 80 점 이상에 대한 boolean indexing  AND  수학점수 90 점 이상에 대한 boolean indexing --> cond 저장
# cond를 df 데이터프레임에 넣어 조회하기

cond = ( df[ '국어' ] >= 80 ) & ( df[ '수학' ] >= 90 )
df[ cond ]

    이름          고향    키   국어   영어   수학  과학  사회     기술
0   루피    Eastblue  174   90   85  100  95  85   레드호크
5   쵸파   Grandline   90   80  100   95  85  80
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔

In [ ]:
# 국어, 영어, 수학 3과목의 점수를 합쳐 '핵심과목' 컬럼에 저장하세요.

df[ '핵심과목' ] = df[ '국어' ] + df[ '영어' ] + df[ '수학' ]  
df

    이름          고향    키   국어   영어   수학  과학  사회     기술  핵심과목
0   루피    Eastblue  174   90   85  100  95  85   레드호크   275
1   조로   Northblue  181   40   35   50  55  25    아수라   125
2   상디   Northblue  180   80   75   70  80  75  디아블잠브   225
3   나미    Eastblue  170   40   60   70  75  80          170
4   우솝   Grandline  173   15   20   10  35  10           45
5   쵸파   Grandline   90   80  100   95  85  80          275
6   로빈       OHARA  188   55   65   45  40  35    풀루르   165
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔   275

In [ ]:
# 국어, 영어, 수학 3과목의 점수을 합치고 평균을 구해  '핵심평균' 컬럼에 저장하세요.

df[ '핵심평균' ] = df[ '핵심과목' ] / 3
df

    이름          고향    키   국어   영어   수학  과학  사회     기술  핵심과목       핵심평균
0   루피    Eastblue  174   90   85  100  95  85   레드호크   275  91.666667
1   조로   Northblue  181   40   35   50  55  25    아수라   125  41.666667
2   상디   Northblue  180   80   75   70  80  75  디아블잠브   225  75.000000
3   나미    Eastblue  170   40   60   70  75  80          170  56.666667
4   우솝   Grandline  173   15   20   10  35  10           45  15.000000
5   쵸파   Grandline   90   80  100   95  85  80          275  91.666667
6   로빈       OHARA  188   55   65   45  40  35    풀루르   165  55.000000
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔   275  91.666667

In [ ]:
# 이름 컬럼을 삭제하세요. 

df.drop( '이름', axis=1 )

           고향    키   국어   영어   수학  과학  사회     기술  핵심과목       핵심평균
0    Eastblue  174   90   85  100  95  85   레드호크   275  91.666667
1   Northblue  181   40   35   50  55  25    아수라   125  41.666667
2   Northblue  180   80   75   70  80  75  디아블잠브   225  75.000000
3    Eastblue  170   40   60   70  75  80          170  56.666667
4   Grandline  173   15   20   10  35  10           45  15.000000
5   Grandline   90   80  100   95  85  80          275  91.666667
6       OHARA  188   55   65   45  40  35    풀루르   165  55.000000
7  Waterseven  240  100   85   90  95  95  라디컬 빔   275  91.666667

<br>

# **정리**
배운 내용을 정리해 보겠습니다. 
- DataFrame 정의 : DataFrame은 2차원(col과 row을 가짐)테이블 데이터 구조를 가지는 자료형
- DataFrame 생성 : read_csv()
- DataFrame 내용 확인 : head(), tail(), info(), shape, columns, index, values, descrbe()
- DataFrame 조회하기 : loc, iloc 
- DataFrame  boolean indexing으로 원하는 row 선택하기
- DataFrame  추가, 삭제하기(drop)
- 위에서 배운 데이터프레임 내용들을 굉장히 많이 자주 사용하므로 많은 연습해 주시기 바랍니다.