# **Pandas 이해 및 활용 - DataFrame 병합하기**

- 두개 이상의 데이터프레임을 합치는 방법에 대해서 알아 보겠습니다.
- 두개 이상의 데이터프레임을 합치는 방법에는 concat() 함수와 merge() 함수가 대표적입니다.
- concat 함수는 주로 동일한 컬럼명을 가지고 있을때 위,아래로 합칠때 많이 사용합니다.
- merge 함수는 2개의 데이터프레임의 공통된 컬럼을 키로해서 합쳐 merge 하게 됩니다.
- 보다 자세한 내용은 아래 실습을 통해서 확인해 보도록 하겠습니다.

<br>

# __1. concat함수 활용__

두 개 이상의 데이터프레임을 하나로 합치는 데이터 병합(merge)이나 연결(concatenate)을 지원합니다.

In [1]:
import pandas as pd
import numpy as np

### <b>1-1. concat 함수 사용하여 DataFrame 병합하기</b>

> - pandas.concat 함수  (배열결합 : concatenate)
>  - 데이터의 속성 형태가 동일한 데이터 셋 끼리 합칠때 사용
> - 열 or 행 레벨로 병합하는 것

#### <b>1) column명이 같은 2개의 데이터프레임을 합칠 경우</b>
>  ignore_index, axis 활용

In [2]:
# 컬럼명이 동일한 2개의 데이터프레임 만들기
# 다만, 컬럼명은 같지만, 인덱스 번호는 다르다. 

df1 = pd.DataFrame({'key1' : [0,1,2,3,4], 'value1' : ['a', 'b', 'c','d','e']}, index=[0,1,2,3,4])
df2 = pd.DataFrame({'key1' : [3,4,5,6,7], 'value1' : ['c','d','e','f','g']}, index=[3,4,5,6,7])

In [3]:
# 컬럼명 key1과 value1로 되어 잇고, 인덱스는 0,1,2,3,4 표시되고 있다.
df1

   key1 value1
0     0      a
1     1      b
2     2      c
3     3      d
4     4      e

In [4]:
# 컬럼명 key1과 value1로 되어 잇고, 인덱스는 3,4,5,6,7 표시되고 있다.
df2

   key1 value1
3     3      c
4     4      d
5     5      e
6     6      f
7     7      g

> ##### __concat함수 옵션__

> - **ignore_index** : 기존 index를 무시하고자 하는 경우
>   - False : 기존 index유지(default) / True : 기존 index무시(index재배열)
> - **axis**
>   - 0 : 위+아래로 합치기(row레벨) / 1 : 왼쪽+오른쪽으로 합치기(col레벨)

In [5]:
# concat 함수를 이용해서 df1, df2 2개의 데이터프레임을 위아래로 즉, 행방향으로 합쳐 보자. 
# 실행결과 df1, df2 2개의 데이터프레임이 위아래로 합쳐진것을 확인할수 있으며
# 인덱스번호가 df1과 df2에서 가지고 있던 인덱스를 그래도 유지하고 있음을 알수 있다. 
# 기본적으로 ignore_index=False 되어 있어, 기존 인덱스를 유지하게 된다. 

pd.concat( [df1, df2] )

   key1 value1
0     0      a
1     1      b
2     2      c
3     3      d
4     4      e
3     3      c
4     4      d
5     5      e
6     6      f
7     7      g

In [6]:
# 이번에도 concat 함수를 이용해서 df1, df2 2개의 데이터프레임을 위아래로 즉, 행방향으로 합쳐 보자. 
# 다만, ignore_index=True 옵션을 주면 어떻게 되는지 확인해 보자.
# 실행 결과, 인덱스가 초기화되어 0번부터 쭉 나열되어 있음을 확인해 볼수 있다.

pd.concat( [df1, df2] , ignore_index=True )

   key1 value1
0     0      a
1     1      b
2     2      c
3     3      d
4     4      e
5     3      c
6     4      d
7     5      e
8     6      f
9     7      g

In [7]:
# 이번에는 concat 함수를 이용해서 df1, df2 2개의 데이터프레임을 왼쪽오른쪽으로 즉, 열방향으로 합쳐 보자.
# 열방향으로 합쳐야 되므로 axis=1 사용해서 합쳐야 합니다. 
# 실행 결과를 보니, 인덱스 번호를 기준으로 해서 df1과 df2 둘다 인덱스 번호가 있으면 왼쪽오른쪽으로 합쳐지고,
# 한쪽에만 인덱스 번호가 있는 경우에는 인덱스 번호 있는쪽의 데이터만 보이고 없는쪽은 NaN 널로 보여 줍니다. 
# 그리고, df1과 df2 데이터프레임을 왼쪽오른쪽으로 열방향으로 합쳐서 key1, value1 컬럼명이 중복해서 보여주고 있습니다. 

pd.concat( [df1, df2], axis =1 )

   key1 value1  key1 value1
0   0.0      a   NaN    NaN
1   1.0      b   NaN    NaN
2   2.0      c   NaN    NaN
3   3.0      d   3.0      c
4   4.0      e   4.0      d
5   NaN    NaN   5.0      e
6   NaN    NaN   6.0      f
7   NaN    NaN   7.0      g

#### <b>2) column명이 다른 경우</b>

> * concat함수중에 join에 대한이해
> * join 방식은 outer의 경우 합집합, inner의 경우 교집합을 의미

In [9]:
# df3과 df4 데이터프레임 만들기 
# 2개의 데이터프레임을 비교해 보니, 컬럼이 같은것도 있고 다른것도 있으며
# 인덱스 번호도 같지 않음을 알수 있다. 

df3 = pd.DataFrame({'a':['a0','a1','a2', 'a3'], 'b':['b0','b1','b2','b3'], 'c':['c0','c1','c2','c3']}, index = [0,1,2,3])
df4 = pd.DataFrame({'a':['a2','a3','a4', 'a5'], 'c':['c2','c3','c4','c5'], 'd':['d1','d2','d3','d4']}, index = [2,3,4,5])

In [10]:
# 컬럼명 a,b,c가 있고 인덱스는 0,1,2,3으로 표시되고 있다.
df3

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [12]:
# 컬럼명 a,c,d가 있고 인덱스는 2,3,4,5으로 표시되고 있다.
df4

    a   c   d
2  a2  c2  d1
3  a3  c3  d2
4  a4  c4  d3
5  a5  c5  d4

In [13]:
# concat 함수를 이용해서 df3과 df4 2개의 데이터프레임을 위아래로 즉, 행방향 axis=0 으로 합쳐 보겠습니다.
# 마찬가지로 기존에 가지고 있던 인덱스 번호가 유지되고 있으며(ignore_index=True)
# df3과 df4 2개의 데이터프레임을 위아래로 합쳐 진것을 확인할수 있습니다. 
# 위아래로 합칠때, 같지 않은 컬럼명에 대해서는 NaN 널로 표시되고 있습니다. 

pd.concat( [df3, df4], axis=0 )

    a    b   c    d
0  a0   b0  c0  NaN
1  a1   b1  c1  NaN
2  a2   b2  c2  NaN
3  a3   b3  c3  NaN
2  a2  NaN  c2   d1
3  a3  NaN  c3   d2
4  a4  NaN  c4   d3
5  a5  NaN  c5   d4

In [15]:
# concat 함수를 이용해서 df3과 df4 2개의 데이터프레임을 왼쪽오른쪽 즉, 열방향 axis=1 으로 합쳐 보겠습니다.
# 실행 결과를 보니, 인덱스 번호를 기준으로 해서 df3과 df4 데이터프레임이 왼쪽오른쪽으로 합쳐지고
# 없는 인덱스에 대해서는 NaN 널로 표시하고 있습니다.
# 그리고, df3과 df4 데이터프레임을 왼쪽오른쪽으로 열방향으로 합쳐서 컬럼명 a, b, c가 중복해서 보여주고 있습니다.

pd.concat( [df3, df4], axis=1 )

     a    b    c    a    c    d
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN
2   a2   b2   c2   a2   c2   d1
3   a3   b3   c3   a3   c3   d2
4  NaN  NaN  NaN   a4   c4   d3
5  NaN  NaN  NaN   a5   c5   d4

<br>

# __2. merge 함수 활용__

### <b>2-1. DataFrame merge</b>

> - Database의 Table들을 Merge/Join하는 것과 유사함
> - 특정한 column(key)을 기준으로 병합
>   - join 방식: how 파라미터를 통해 명시(특정한 col을 바탕으로 join 하는 것)
     - inner: 기본 merge방법, 일치하는 값이 있는 경우 (Merge할 테이블의 데이터가 모두 있는 경우만 가지고 옴)
     - left: left outer join (왼쪽을 기준으로 오른쪽을 채움 - 오른쪽에 데이터 없으면 NaN)
     - right: right outer join
     - outer: full outer join  (Left와 Right를 합한 것)

In [18]:
# customer 데이터프레임과 orders 데이터프레임 만들어 보겠습니다. 
# 자세히 보니, 2개의 데이터프레임에 '고객ID' 컬럼이 공통으로 존재하고 있음을 알수 있습니다.

customer = pd.DataFrame({'고객ID' : np.arange(6), 
                    '이름' : ['철수', '영희', '길동', '영수', '수민', '동건'], 
                    '나이' : [40, 20, 21, 30, 31, 18]})

orders = pd.DataFrame({'고객ID' : [1, 1, 2, 2, 2, 3, 3, 1, 4, 9], 
                    '상품명' : ['치약', '칫솔', '이어폰', '헤드셋', '수건', '생수', '수건', '치약', '생수', '케이스'], 
                    '수량' : [1, 2, 1, 1, 3, 2, 2, 3, 2, 1]})

In [19]:
# customer 데이터프레임은 고객ID, 이름, 나이 컬럼으로 구성됩니다. 
# 그리고 customer 데이터프레임의 '고객ID' 확인해 보니, 0,1,2,3,4,5 있음을 확인할수 있습니다. 

customer

   고객ID  이름  나이
0     0  철수  40
1     1  영희  20
2     2  길동  21
3     3  영수  30
4     4  수민  31
5     5  동건  18

In [21]:
# orders 데이터프레임은 고객ID, 상품명, 수량 컬럼으로 구성됩니다. 
# 그리고 orders 데이터프레임의'고객ID' 확인해 보니, 1,2,3,4,9 있음을 알수 있습니다. 
# 2개의 데이터프레임을 비교해 보면, 둘다 존재하는 '고객ID'는 1,2,3,4 이며
# customer 데이터프레임의 '고객ID'에는 9번 없으며, orders 데이터프레임의'고객ID' 에는 0번, 5번이 없음을 알수 있습니다. 

orders

   고객ID  상품명  수량
0     1   치약   1
1     1   칫솔   2
2     2  이어폰   1
3     2  헤드셋   1
4     2   수건   3
5     3   생수   2
6     3   수건   2
7     1   치약   3
8     4   생수   2
9     9  케이스   1

#### <b>1) merge함수의 on 옵션</b>

>  - join 대상이 되는 column 명시

In [22]:
# merge 함수를 활용해서 2개의 데이터프레임의 공통컬럼 '고객ID'로 합쳐 보겠습니다. 
# 기본적인 Merge방식은 inner방식으로 같은 '고객ID'만 합쳐지게 됩니다. 
# 즉, 같은 '고객ID' 번호인 1,2,3,4 로만 합쳐지게 됩니다.
# 자세히 보면, customer의 고객ID' 0번, 5번과 orders의 고객ID' 9번이 없는 것을 확인할수 있습니다. 

pd.merge( customer, orders, on='고객ID' )

   고객ID  이름  나이  상품명  수량
0     1  영희  20   치약   1
1     1  영희  20   칫솔   2
2     1  영희  20   치약   3
3     2  길동  21  이어폰   1
4     2  길동  21  헤드셋   1
5     2  길동  21   수건   3
6     3  영수  30   생수   2
7     3  영수  30   수건   2
8     4  수민  31   생수   2

In [23]:
# 위의 실행한것과 똑같은 것으로 , merge 함수를 활용해서 2개의 데이터프레임의 공통컬럼 '고객ID'로 합쳐 보겠습니다. 
# 다만, how 옵션에 'inner' 주어 같은 '고객ID'로만 합쳐 질수 있도록 합니다.
# how 옵션을 안주게 되면 ,기본적으로 how='inner' 됩니다. 

pd.merge( customer, orders, on='고객ID', how='inner' )

   고객ID  이름  나이  상품명  수량
0     1  영희  20   치약   1
1     1  영희  20   칫솔   2
2     1  영희  20   치약   3
3     2  길동  21  이어폰   1
4     2  길동  21  헤드셋   1
5     2  길동  21   수건   3
6     3  영수  30   생수   2
7     3  영수  30   수건   2
8     4  수민  31   생수   2

In [26]:
# 이번에는 how='left' 옵션을 주어 왼쪽 테이블(customer기준)을 기준으로 Merge 실행해 보도록 하겠습니다. 
# 왼쪽 테이블 기준으로 하면, 무조건 왼쪽 테이블 customer의 '고객ID'는 다 나오게 되며, 
# 즉, 고객ID가 0,1,2,3,4,5번까지 나오게 되며, orders 테이블에만 존재하는 '고객ID' 9번은 보이지 않게 됩니다.
# 합쳐질때 없는 부분은 NaN 널로 표시되고 있습니다. 

pd.merge( customer, orders, on='고객ID', how='left' )

    고객ID  이름  나이  상품명   수량
0      0  철수  40  NaN  NaN
1      1  영희  20   치약  1.0
2      1  영희  20   칫솔  2.0
3      1  영희  20   치약  3.0
4      2  길동  21  이어폰  1.0
5      2  길동  21  헤드셋  1.0
6      2  길동  21   수건  3.0
7      3  영수  30   생수  2.0
8      3  영수  30   수건  2.0
9      4  수민  31   생수  2.0
10     5  동건  18  NaN  NaN

In [28]:
# 이번에는 how='right' 옵션을 주어 오른쪽 테이블(orders기준)을 기준으로 Merge 실행해 보도록 하겠습니다. 
# 오른쪽 테이블 기준으로 하면, 무조건 오른쪽 테이블 orders의 '고객ID'는 다 나오게 되며, 
# 즉, 고객ID가 1,2,3,4,9번까지 나오게 되며, customer 테이블에만 존재하는 '고객ID' 0번과 5번은 보이지 않게 됩니다.
# 합쳐질때 없는 부분은 NaN 널로 표시되고 있습니다. 

pd.merge(customer, orders, on='고객ID', how='right')

   고객ID   이름    나이  상품명  수량
0     1   영희  20.0   치약   1
1     1   영희  20.0   칫솔   2
2     2   길동  21.0  이어폰   1
3     2   길동  21.0  헤드셋   1
4     2   길동  21.0   수건   3
5     3   영수  30.0   생수   2
6     3   영수  30.0   수건   2
7     1   영희  20.0   치약   3
8     4   수민  31.0   생수   2
9     9  NaN   NaN  케이스   1

In [29]:
# outer : Left와 Right를 합친 것
# 이번에는 how='outer' 옵션을 주어 Merge 실행해 보도록 하겠습니다. 
# 실행결과를 보면 왼쪽과 오른쪽 테이블의 '고객ID'는 다 나오게 되며
# 합쳐질때 없는 부분은 NaN 널로 표시되고 있습니다. 

pd.merge(customer, orders, on='고객ID', how='outer')

    고객ID   이름    나이  상품명   수량
0      0   철수  40.0  NaN  NaN
1      1   영희  20.0   치약  1.0
2      1   영희  20.0   칫솔  2.0
3      1   영희  20.0   치약  3.0
4      2   길동  21.0  이어폰  1.0
5      2   길동  21.0  헤드셋  1.0
6      2   길동  21.0   수건  3.0
7      3   영수  30.0   생수  2.0
8      3   영수  30.0   수건  2.0
9      4   수민  31.0   생수  2.0
10     5   동건  18.0  NaN  NaN
11     9  NaN   NaN  케이스  1.0

<br>

#### <b>질문) 가장 많이 팔린 상품명은 무엇일까요?</b>
  - Hint : merge, groupby, sort_values 활용

In [32]:
# 많이 팔린 아이템을 찾아아 하므로 orders 데이터프레임이 중심이 되도록 merge 해야 함.
# merge된 데이터를 보니, 어떤 고객이 어떤 상품을 몇개 구매했는지 알수 있다.
# 많이 팔린 상품을 알기 위해서는 상품별로 그룹화해서 상품별로 합해서 몇개 팔렸는지 알수 있겠다. 

pd.merge(customer, orders, on='고객ID', how='right')

   고객ID   이름    나이  상품명  수량
0     1   영희  20.0   치약   1
1     1   영희  20.0   칫솔   2
2     2   길동  21.0  이어폰   1
3     2   길동  21.0  헤드셋   1
4     2   길동  21.0   수건   3
5     3   영수  30.0   생수   2
6     3   영수  30.0   수건   2
7     1   영희  20.0   치약   3
8     4   수민  31.0   생수   2
9     9  NaN   NaN  케이스   1

In [33]:
#  2개의 customer, orders 데이터프레임을 right 조인으로 합쳐서 cust_order 데이터프레임에 저장하고
# '상품명'으로 그룹화 및 합계 출력해 보겠습니다. 
# 출력결과를 보니, '수건' 상품이 5개로 제일 많이 팔린것을 알수 있습니다. 
# 수량이 정렬되었으면 보기 좋겠네요.

cust_order = pd.merge(customer, orders, on='고객ID', how='right')
cust_order.groupby('상품명').sum()

     고객ID    나이  수량
상품명
생수      7  61.0   4
수건      5  51.0   5
이어폰     2  21.0   1
치약      2  40.0   4
칫솔      1  20.0   2
케이스     9   0.0   1
헤드셋     2  21.0   1

In [35]:
# 그룹화된 결과를 sort_values 함수를 이용해서 정렬해 보겠습니다. 

cust_order.groupby('상품명').sum().sort_values('수량', ascending=False)

     고객ID    나이  수량
상품명
수건      5  51.0   5
생수      7  61.0   4
치약      2  40.0   4
칫솔      1  20.0   2
이어폰     2  21.0   1
케이스     9   0.0   1
헤드셋     2  21.0   1

#### <b>질문) 영희가 가장 많이 구매한 상품명은 무엇일까요?</b>
   - 고객별, 상품명별로 그룹화 
   - loc을 활용하여 (영희의 row의 수량 확인)

In [40]:
# 1. 고객이 구매한 아이템이 있어야 하므로 , 2개의 데이터프레임을 inner 조인으로 합쳐야 합니다.
pd.merge(customer, orders, on='고객ID', how='inner')

   고객ID  이름  나이  상품명  수량
0     1  영희  20   치약   1
1     1  영희  20   칫솔   2
2     1  영희  20   치약   3
3     2  길동  21  이어폰   1
4     2  길동  21  헤드셋   1
5     2  길동  21   수건   3
6     3  영수  30   생수   2
7     3  영수  30   수건   2
8     4  수민  31   생수   2

In [41]:
# 2. 조인결과를 고객별, 상품별로 합산해서 몇개 구매했는지 보여주도록 그룹화 해야 됩니다.
pd.merge(customer, orders, on='고객ID', how='inner').groupby(['이름', '상품명']).sum()

        고객ID  나이  수량
이름 상품명
길동 수건      2  21   3
   이어폰     2  21   1
   헤드셋     2  21   1
수민 생수      4  31   2
영수 생수      3  30   2
   수건      3  30   2
영희 치약      2  40   4
   칫솔      1  20   2

In [42]:
# 3. 그룹화 결과 출력해서 우리가 원하는 영희의 데이터만 가져오면 됩니다 
pd.merge(customer, orders, on='고객ID', how='inner').groupby(['이름', '상품명']).sum().loc['영희']

     고객ID  나이  수량
상품명
치약      2  40   4
칫솔      1  20   2

<br>

# **[실습] 데이터프레임 병합하기**

1. 아래 2개의 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.    
컬럼명은 ['이름','나이','성별'] 으로 설정하세요.

<pre>
data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남']
]

data2 = [
         ['신사임당',48,'여'], 
         ['장보고',22,'남']
]
    
</pre>

In [8]:
# 아래 딕셔너리를 활용하여 df 데이터프레임을 만드세요.
# 먼저, 판다스 임포트하기

import pandas as pd

In [9]:
# 아래 2개의 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.    
# 컬럼명은 ['이름','나이','성별'] 으로 설정하세요.

data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남']
]

data2 = [
         ['신사임당',48,'여'], 
         ['장보고',22,'남']
]

df1 = pd.DataFrame( data1, columns=['이름','나이','성별'] )
df2 = pd.DataFrame( data2, columns=['이름','나이','성별'] )

In [10]:
# df1 데이터프레임 보기
df1

    이름  나이 성별
0  홍길동  23  남
1  이순신  55  남

In [11]:
# df2 데이터프레임 보기 : df1과 df2 데이터프레임이 같은 컬럼명으로 구성되어 있음 확인
df2

     이름  나이 성별
0  신사임당  48  여
1   장보고  22  남

In [12]:
# concat 함수를 사용해서 위아래로 합쳐 보기
# 컬럼을 기준으로 위아래로 합치게 됨.

pd.concat( [ df1, df2 ] , axis=0 )

     이름  나이 성별
0   홍길동  23  남
1   이순신  55  남
0  신사임당  48  여
1   장보고  22  남

In [13]:
# concat 함수를 사용해서 위아래로 합쳐 보기
# ignore_index=True 추가해서 인덱스를 새로 만듬.

pd.concat( [ df1, df2 ] , axis=0 , ignore_index=True )

     이름  나이 성별
0   홍길동  23  남
1   이순신  55  남
2  신사임당  48  여
3   장보고  22  남

<br>

2. 아래 2개의 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.    

<pre>
data1 = [
         [23,'남'],
         [55,'남'], 
         [48,'여']
]

columns = ['나이','성별']
index = ['홍길동','이순신','신사임당']


data2 = [
         ['서울',3], 
         ['경기', 1]
]

columns = ['주소','학년']
index = ['홍길동','신사임당']
    
</pre>

In [19]:
# 아래 2개의 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.    

data1 = [
         [23,'남'],
         [55,'남'], 
         [48,'여']
]

data2 = [
         ['서울',3], 
         ['경기', 1]
]

df1 = pd.DataFrame( data1, columns=['나이','성별'], index=['홍길동','이순신','신사임당'] ) 
df2 = pd.DataFrame( data2, columns=['주소','학년'], index=['홍길동','신사임당'] )

In [20]:
# df1 데이터프레임 보기 : 인덱스가 숫자가 아닌, 이름으로 되어 잇음
df1

      나이 성별
홍길동   23  남
이순신   55  남
신사임당  48  여

In [17]:
# df2 데이터프레임 보기 : 인덱스가 숫자가 아닌 이름으로 되어 있으며, df1과 df2의 인덱스가 일치되는 부분이 보임.
df2

      주소  학년
홍길동   서울   3
신사임당  경기   1

In [22]:
# concat 함수를 사용해서 왼쪽오른쪽으로 합쳐 보기
# 인덱스를 기준으로 2개의 데이터프레임을 왼쪽오른쪽으로 합치게 됨.
# 인덱스가 일치되지 않은 부분은 NaN으로 표시됨.

pd.concat( [ df1, df2 ] , axis=1 )

      나이 성별   주소   학년
홍길동   23  남   서울  3.0
이순신   55  남  NaN  NaN
신사임당  48  여   경기  1.0

<br>

3. 아래 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.    

<pre>
data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남'], 
         ['신사임당',48,'여']
]

columns=['이름','나이','성별']

data2 = [
         ['홍길동','터미네이터',5],
         ['홍길동','비긴어게인',2], 
         ['홍길동','살인의추억',4], 
         ['신사임당','비긴어게인',5],
         ['장보고','살인의추억',3]
]

columns=['이름','나이','성별']

</pre>

In [23]:
# 아래 리스트를 활용하여 df1과 df2 데이터프레임을 만드세요.
# 컬럼명은 ['이름','나이','성별'] 으로 설정하세요.

data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남'], 
         ['신사임당',48,'여']
]

data2 = [
         ['홍길동','터미네이터',5],
         ['홍길동','비긴어게인',2], 
         ['홍길동','살인의추억',4], 
         ['신사임당','비긴어게인',5],
         ['장보고','살인의추억',3]
]

df1 = pd.DataFrame( data1, columns=['이름','나이','성별'] )   
df2 = pd.DataFrame( data2, columns=['이름','영화','평점'] )

In [24]:
# df1 데이터프레임 보기 
# 컬럼명이 이름, 나이 , 성별로 되어 있음

df1

     이름  나이 성별
0   홍길동  23  남
1   이순신  55  남
2  신사임당  48  여

In [25]:
# df2 데이터프레임 보기
# 컬러몀이 이름, 영화, 평점으로 되어 있으며
# df1과 df2 데이터프레임에서 이름 컬럼이 공통으로 들어가 있어 , key로 사용 가능하다.

df2

     이름     영화  평점
0   홍길동  터미네이터   5
1   홍길동  비긴어게인   2
2   홍길동  살인의추억   4
3  신사임당  비긴어게인   5
4   장보고  살인의추억   3

In [27]:
# 이름 컬럼을 key로 해서 df1과 df2 데이터프레임 merge 하기
# how='inner'

pd.merge( df1,df2, on='이름', how='inner' )

     이름  나이 성별     영화  평점
0   홍길동  23  남  터미네이터   5
1   홍길동  23  남  비긴어게인   2
2   홍길동  23  남  살인의추억   4
3  신사임당  48  여  비긴어게인   5

In [28]:
# 이름 컬럼을 key로 해서 df1과 df2 데이터프레임 merge 하기
# how='left' --> df1 기준으로 하기에 df2에만 있는 장보고 이름은 보이지 않게 됨.

df1.merge(df2, on='이름',how='left')

     이름  나이 성별     영화   평점
0   홍길동  23  남  터미네이터  5.0
1   홍길동  23  남  비긴어게인  2.0
2   홍길동  23  남  살인의추억  4.0
3   이순신  55  남    NaN  NaN
4  신사임당  48  여  비긴어게인  5.0

In [29]:
# 이름 컬럼을 key로 해서 df1과 df2 데이터프레임 merge 하기
# how='right' --> df2 기준으로 하기에 df2에만 있는 장보고 이름은 보이고, df1에만 있는 이순신 이름이 보이지 않게 됨.

df1.merge(df2, on='이름',how='right')

     이름    나이   성별     영화  평점
0   홍길동  23.0    남  터미네이터   5
1   홍길동  23.0    남  비긴어게인   2
2   홍길동  23.0    남  살인의추억   4
3  신사임당  48.0    여  비긴어게인   5
4   장보고   NaN  NaN  살인의추억   3

In [31]:
# 이름 컬럼을 key로 해서 df1과 df2 데이터프레임 merge 하기
# how='outer' --> 이름 컬럼을 key로 매칭이 되지 않는 df1에만 있는 이순신, df2에만 있는 장보고 모두가 출력됨.

df1.merge(df2, on='이름',how='outer')

     이름    나이   성별     영화   평점
0   홍길동  23.0    남  터미네이터  5.0
1   홍길동  23.0    남  비긴어게인  2.0
2   홍길동  23.0    남  살인의추억  4.0
3   이순신  55.0    남    NaN  NaN
4  신사임당  48.0    여  비긴어게인  5.0
5   장보고   NaN  NaN  살인의추억  3.0

In [32]:
# 이름 컬럼을 key로 해서 df1과 df2 데이터프레임 merge 하기
# how='inner'
# df3 데이터프레임으로 저장

df3 = pd.merge( df1,df2, on='이름', how='inner' )
df3

     이름  나이 성별     영화  평점
0   홍길동  23  남  터미네이터   5
1   홍길동  23  남  비긴어게인   2
2   홍길동  23  남  살인의추억   4
3  신사임당  48  여  비긴어게인   5

In [34]:
# 이름별, 영화별로 평점의 합을 구하기 

pd.pivot_table( data=df3, index='이름', columns='영화', values='평점', aggfunc='sum' )

영화    비긴어게인  살인의추억  터미네이터
이름
신사임당    5.0    NaN    NaN
홍길동     2.0    4.0    5.0

<br>

# __3. 정리__

- 두개 이상의 데이터프레임을 합치는 방법에 대해서 알아 보았습니다.
- 두개 이상의 데이터프레임을 합치는 방법에는 concat() 함수와 merge() 함수가 대표적으로 사용되며
- concat 함수는 주로 동일한 컬럼명을 가지고 있을때 위,아래로 합칠때 많이 사용합니다.
- merge 함수는 2개의 데이터프레임의 공통된 컬럼을 키로 해서 합쳐 merge 하게 되며
- 합치는 방법에 따라 inner, left, right, outer 방법이 있었습니다.
- 자주 사용하지 않지만, 2개 이상의 데이터프레임을 합쳐야 하는경우가 생기므로
- 사용법을 익혀 두고 , 필요할때마다 인터넷 검색을 해서 매뉴얼을 찾아보고 사용하면 되겠습니다.