# 실습 1

- 아래 딕셔너리를 활용하여 DataFrames를 만들어라.

```
data = {
    '이름' : ['루피', '조로', '상디', '나미', '우솝', '쵸파', '로빈', '프랑키'],
    '고향' : ['Eastblue','Northblue','Northblue', 'Eastblue', 'Grandline', 'Grandline', 'OHARA', 'Waterseven'],
    '키' : [174, 181, 180, 170, 173, 90, 188, 240],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    '기술' : ['레드호크', '아수라', '디아블잠브', '', '', '', '풀루르', '라디컬 빔']   
}
```

In [1]:
import pandas as pd

# 1. 아래 딕셔너리를 활용하여 df 데이터프레임을 만들어라.
data = {
    '이름' : ['루피', '조로', '상디', '나미', '우솝', '쵸파', '로빈', '프랑키'],
    '고향' : ['Eastblue','Northblue','Northblue', 'Eastblue', 'Grandline', 'Grandline', 'OHARA', 'Waterseven'],
    '키' : [174, 181, 180, 170, 173, 90, 188, 240],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    '기술' : ['레드호크', '아수라', '디아블잠브', '', '', '', '풀루르', '라디컬 빔']   
}

df = pd.DataFrame(data)
df

    이름          고향    키   국어   영어   수학  과학  사회     기술
0   루피    Eastblue  174   90   85  100  95  85   레드호크
1   조로   Northblue  181   40   35   50  55  25    아수라
2   상디   Northblue  180   80   75   70  80  75  디아블잠브
3   나미    Eastblue  170   40   60   70  75  80
4   우솝   Grandline  173   15   20   10  35  10
5   쵸파   Grandline   90   80  100   95  85  80
6   로빈       OHARA  188   55   65   45  40  35    풀루르
7  프랑키  Waterseven  240  100   85   90  95  95  라디컬 빔

In [17]:
# 2. 앞쪽 5개 데이터 보기
df.head()

# 3. 뒤쪽 5개 데이터 보기
df.tail()

# 4. info 보기
df.info()

# 5. 통계정보 보기
df.describe()

# 6. shape 정보 보기
df.shape # (8, 9)

# 7. index 보기
df.index # RangeIndex(start=0, stop=8, step=1)

# 8. columns 보기
df.columns # Index(['이름', '고향', '키', '국어', '영어', '수학', '과학', '사회', '기술'], dtype='str')

# 9. columns의 마지막 2개의 컬럼만 뽑아내기 ⭐️
df.columns[-2:] # Index(['사회', '기술'], dtype='str')

# 10. values 보기
df.values

# 11. 키컬럼과 영어컬럼만 보기
df[['키', '영어']]

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   고향      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   기술      8 non-null      str
dtypes: int64(6), str(3)
memory usage: 708.0 bytes

     키   영어
0  174   85
1  181   35
2  180   75
3  170   60
4  173   20
5   90  100
6  188   65
7  240   85

In [25]:
# 12. 5번 인덱스의 '국어' 컬럼의 값 확인하기 ⭐️
df.loc[5, '국어'] # 80

# 13. 국어 점수가 80 이상인 데이터만 뽑아 조회
con_isAbove80inKorean = df['국어'] >= 80
df[con_isAbove80inKorean]

# 14. 국어 점수가 80 이상이고 수학 점수가 90 이상인 데이터만 뽑아 조회
con_isAbove90inMath = df['수학'] >= 90
df[con_isAbove80inKorean & con_isAbove90inMath]

# 15. 국어, 영어, 수학 3과목의 점수를 합쳐 '핵심과목' 컬럼에 저장
df['핵심과목'] = df['국어'] + df['수학'] + df['영어']
df

# 16. 국어, 영어, 수학 3과목의 점수로 '핵심평균' 컬럼에 저장
df['핵심평균'] = df['핵심과목'] / 3
df

# 17. 이름 컬럼 삭제하기 ⭐️
df.drop('이름', axis=1)

           고향    키   국어   영어   수학  과학  사회     기술  핵심과목       핵심평균
0    Eastblue  174   90   85  100  95  85   레드호크   275  91.666667
1   Northblue  181   40   35   50  55  25    아수라   125  41.666667
2   Northblue  180   80   75   70  80  75  디아블잠브   225  75.000000
3    Eastblue  170   40   60   70  75  80          170  56.666667
4   Grandline  173   15   20   10  35  10           45  15.000000
5   Grandline   90   80  100   95  85  80          275  91.666667
6       OHARA  188   55   65   45  40  35    풀루르   165  55.000000
7  Waterseven  240  100   85   90  95  95  라디컬 빔   275  91.666667