# 실습 1

- 아래 딕셔너리를 활용하여 질문에 답하라.
```
data = {
          "지점": ["A", "A", "B", "B"],
          "상품": ["P1", "P2", "P1", "P2"],
          "Q1": [112, 134, 156, 178],
          "Q2": [212, 234, 256, 278],
          "Q3": [312, 334, 356, 378],
          "Q4": [412, 434, 456, 478]
}
```

In [2]:
# 1. 해당 딕셔너리를 활용해 df 데이터프레임을 만들고 내용 조회하기
import pandas as pd
import numpy as np

data = {
          "지점": ["A", "A", "B", "B"],
          "상품": ["P1", "P2", "P1", "P2"],
          "Q1": [112, 134, 156, 178],
          "Q2": [212, 234, 256, 278],
          "Q3": [312, 334, 356, 378],
          "Q4": [412, 434, 456, 478]
}
df = pd.DataFrame(data)
df

  지점  상품   Q1   Q2   Q3   Q4
0  A  P1  112  212  312  412
1  A  P2  134  234  334  434
2  B  P1  156  256  356  456
3  B  P2  178  278  378  478

In [19]:
# 2. df 데이터프레임 앞쪽 5개 데이터 보기
df.head()

  지점  상품   Q1   Q2   Q3   Q4
0  A  P1  112  212  312  412
1  A  P2  134  234  334  434
2  B  P1  156  256  356  456
3  B  P2  178  278  378  478

In [20]:
# 3. df 데이터프레임 뒤쪽 5개 데이터 보기
df.tail()

  지점  상품   Q1   Q2   Q3   Q4
0  A  P1  112  212  312  412
1  A  P2  134  234  334  434
2  B  P1  156  256  356  456
3  B  P2  178  278  378  478

In [21]:
# 4. df 데이터프레임 shape 정보 보기
df.shape

(4, 6)

In [ ]:
# 5. df 데이터프레임 index 보기 ⭐️
df.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
# 6. df 데이터프레임 columns 보기
df.columns

Index(['지점', '상품', 'Q1', 'Q2', 'Q3', 'Q4'], dtype='str')

In [ ]:
# 7. df 데이터프레임 columns에 대해 마지막 2개의 컬럼만 뽑아내기 ⭐️
# df.columns[['Q3', 'Q4']] # 코드 작성 실패, 문법 오류
df.columns[-2:]

Index(['Q3', 'Q4'], dtype='str')

In [29]:
# 8. df 데이터프레임 values 보기
df.values

array([['A', 'P1', 112, 212, 312, 412],
       ['A', 'P2', 134, 234, 334, 434],
       ['B', 'P1', 156, 256, 356, 456],
       ['B', 'P2', 178, 278, 378, 478]], dtype=object)

In [30]:
# 9. df 데이터프레임 info 보기
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지점      4 non-null      str
 1   상품      4 non-null      str
 2   Q1      4 non-null      int64
 3   Q2      4 non-null      int64
 4   Q3      4 non-null      int64
 5   Q4      4 non-null      int64
dtypes: int64(4), str(2)
memory usage: 324.0 bytes

In [ ]:
# 10. '지점' 컬럼 기준 그룹화하고 평균 구하기 ⭐️
# df.groupby(['지점'])[['Q1', 'Q2', 'Q3', 'Q4']].mean() # 숫자 타입만 선택하여 평균 구하기
df.drop('상품', axis=1).groupby('지점').mean() # 숫자 외 타입 제거하여 평균 구하기

       Q1     Q2     Q3     Q4
지점
A   123.0  223.0  323.0  423.0
B   167.0  267.0  367.0  467.0

In [37]:
# 11. '상품' 컬럼 기준 그룹화하고 평균 구하기
df.drop('지점', axis=1).groupby('상품').mean()

       Q1     Q2     Q3     Q4
상품
P1  134.0  234.0  334.0  434.0
P2  156.0  256.0  356.0  456.0

In [ ]:
# 12. pivot_table 활용해 인덱스는 '지점', 컬럼은 '상품', values는 'Q1'으로 평균 구하기 ⭐️
# df.pivot_table(index='지점', columns='상품', values='Q1').mean() # 잘못 작성한 코드
# aggFunc='mean'이므로 mean()할 경우 한 번 더 평균 진행. mean()은 컬럼별 평균 구하는 함수
df.pivot_table(index='지점', columns='상품', values='Q1')
# pd.pivot_table(data=df, index='지점', columns='상품', values='Q1')

상품     P1     P2
지점
A   112.0  134.0
B   156.0  178.0

In [48]:
# 13. df 데이터프레임 '지점' 컬럼을 인덱스로 만들고 df1에 할당하기
df1 = df.set_index('지점')
df1

    상품   Q1   Q2   Q3   Q4
지점
A   P1  112  212  312  412
A   P2  134  234  334  434
B   P1  156  256  356  456
B   P2  178  278  378  478

In [49]:
# 14. df1 데이터프레임 인덱스를 리셋하기
df1.reset_index()

  지점  상품   Q1   Q2   Q3   Q4
0  A  P1  112  212  312  412
1  A  P2  134  234  334  434
2  B  P1  156  256  356  456
3  B  P2  178  278  378  478

In [51]:
# 15. df 데이터프레임 '지점'과 '상품' 2개의 멀티인덱스를 만들고 df2에 저장
df2 = df.set_index(['지점', '상품'])
df2

        Q1   Q2   Q3   Q4
지점 상품
A  P1  112  212  312  412
   P2  134  234  334  434
B  P1  156  256  356  456
   P2  178  278  378  478

In [53]:
# 16. df2 데이터프레임에서 '상품' 인덱스를 컬럼 레벨로 올리기
df2.unstack('상품')

     Q1        Q2        Q3        Q4
상품   P1   P2   P1   P2   P1   P2   P1   P2
지점
A   112  134  212  234  312  334  412  434
B   156  178  256  278  356  378  456  478

In [55]:
# 17. df2 데이터프레임에서 '지점' 인덱스를 컬럼 레벨로 올리고 df3에 저장
df3 = df2.unstack('지점')
df3

     Q1        Q2        Q3        Q4
지점    A    B    A    B    A    B    A    B
상품
P1  112  156  212  256  312  356  412  456
P2  134  178  234  278  334  378  434  478

In [56]:
# 18. df3 데이터프레임에서 '지점' 컬럼을 인덱스 레벨로 내리기
df3.stack('지점')

        Q1   Q2   Q3   Q4
상품 지점
P1 A   112  212  312  412
   B   156  256  356  456
P2 A   134  234  334  434
   B   178  278  378  478