# **머신러닝 모델 템플릿**

<br>

### **TIPS 데이터 활용하여 쉽게 모델링하기**
- 간단하게 쉽게 머신러닝 모델링 만들어 보기
- 원하는 컬럼을 선택해서 회귀 모델, 분류 모델 만들어 보기
- 잘 몰라도 아래 순서에 맞게 , 이런식으로 실행하면 되겠구나 느끼기
- 여러분이 처음 한다고 생각하고 템플릿 작성함

### **모델링 프로세스**
1. 데이터 가져오기
2. 데이터 분석
3. X , y 나누기
4. 머신러닝 모델링

<br>

## **0. tips2.csv 데이터 만들기**

In [ ]:
# !pip install seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


tips = sns.load_dataset('tips')

# tips.sex.replace(['Female', 'Male'], [0,1], inplace=True)
# tips.smoker.replace(['No', 'Yes'], [0,1], inplace=True)
# tips.time.replace(['Dinner', 'Lunch'], [1,0], inplace=True)
# 강의에서는 v2.0 이하라서 위 코드 동작
# 나는 pandas 버전은 v3.0.2로 v2.0 이상이라서 위 코드 동작 불가 (Categorical dtype 에러 발생)
# https://pandas.pydata.org/docs/user_guide/categorical.html 참고
# tips.dtypes으로 sex, smoker, time 컬럼이 str, object가 아닌 category임을 확인. replace 대신 map 사용
tips['sex']    = tips['sex'].map({'Female': 0, 'Male': 1})
tips['smoker'] = tips['smoker'].map({'No': 0, 'Yes': 1})
tips['time']   = tips['time'].map({'Dinner': 1, 'Lunch': 0})

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
tips.day = le.fit_transform(tips.day)

tips.to_csv('tips2.csv', index=False)

<br>
<br>
<br>

---

## **1. 데이터 가져오기**
- 먼저, 데이터가 있어야 모델링을 만들수 있다.
- 데이터 가져오는 방법에는 여러가지 있다.
 - 본인 데이터를 직접 올리는 방법
 - 기존에 제공하는 데이터 가져다 쓰는 방법
- 반드시 데이터를 읽어와야 후속 작업을 할수 있다.

In [15]:
# 필요한 라이브러리 가져오기
# 그냥 무조건 가져온다고 생각하자 : pandas, numpy, seaborn, matplotlib.pyplot
# seaborn 설치가 되어 있지 않으면 라이브러리는 설치 필요 : !pip install seaborn
# !pip install seaborn

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# 우리는 직접 데이터를 가지고 실습을 진행한다.
# 파일명 : tips2.csv
# 판다스에서 csv 파일을 읽는 함수는 뭘까? 외우면 좋다. 못외웠다면?
# 먼저, 판다스에 있는 함수를 찾는다.  그냥 외워라!!

dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

In [4]:
#  판다스의 read_csv 함수를 찾았는데, 사용법을 모른다면
# 1. 아래와 같이 help 찾는다. ? , shift+Tab 2가지 방법으로 쥬피터 노트북에서 help을 볼수 있다.
# 2. 구글링 : pandas read_csv --> 판다스 사이트 접속해서 도움말 보기 : https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[HashableT, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names:
    if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.

    When inferred from the file contents, headers are kept distinct from
    each other by renaming duplicate names with a numeric suffix of the form
    ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
    Empty headers are named ``"Unnamed: {i}"`` or ``
    "Unnamed: {i}_level_{level}"``
    in the case of MultiIndex columns.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
    Column(s) to use as row label(s), denoted either by column labels or column
    indices.  If a sequence of labels or indices is given,
    :class:`~pandas.MultiIndex`
    will be formed for the row labels.

    Note: ``index_col=False`` can be used to force pandas to *not* use the first
    column as the index, e.g., when you have a malformed file with delimiters at
    the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either
    by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s).
    If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion. Specify a ``defaultdict`` as input where
    the default determines the ``dtype``
    of the columns which are not explicitly
    listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster,
    while the python engine
    is currently more feature-complete. Multithreading
    is currently only supported by
    the pyarrow engine. Some features of the "pyarrow" engine
    are unsupported or may not work correctly.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition
    to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive
    variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False``
    otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
    Refers to the number of data rows in the returned DataFrame, excluding:

    * The header row containing column names.
    * Rows before the header row, if ``header=1`` or larger.

    Example usage:

    * To read the first 999,999 (non-header) rows:
      ``read_csv(..., nrows=999999)``

    * To read rows 1,000,000 through 1,999,999:
      ``read_csv(..., skiprows=1000000, nrows=999999)``

na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
    optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict``
    passed, specific
    per-column ``NA`` values.  By default the following values
    are interpreted as
    ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
    representations of missing data.
keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values``
      are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``,
    the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, None, list of Hashable, default None
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index.
    * ``None``. Behaves like ``True`` if ``date_format`` is specified.
    * ``list`` of ``int`` or names.
      e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates and/or times when
    used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"`` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data.
    If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only
    one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
    ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for
    Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
    2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
    only fields containing special
    characters are quoted (e.g., characters defined
    in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
    When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
    whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
    field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are:

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is
      encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when
      they are encountered.
    - Callable, function that will process a single bad line.
        - With ``engine='python'``, function with signature
          ``(bad_line: list[str]) -> list[str] | None``.
          ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with
          more elements than
          expected, a ``ParserWarning`` will be emitted while
          dropping extra elements.
        - With ``engine='pyarrow'``, function with signature
          as described in pyarrow documentation: `invalid_row_handler
          <https://arrow.apache.org/docs/python
          /generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

    .. versionchanged:: 2.2.0

        Callable for ``engine='pyarrow'``

low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set ``False``, or specify the type with the ``dtype`` parameter.
    Note that the entire file is read into a single :class:`~pandas.DataFrame`
    regardless, use the ``chunksize`` or ``iterator``
    parameter to return the data in
    chunks. (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for ``filepath_or_buffer``, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : {'high', 'legacy', 'round_trip'}, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or ``'high'`` for the ordinary converter,
    ``'legacy'`` for the original lower precision pandas converter, and
    ``'round_trip'`` for the round-trip converter.

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior

In [ ]:
# 글 완성 기능 활용 : 함수명 쓰다가 Tab 키를 누르면 관련된 함수명들 나열됨
# read 뒤에 커서 위치하고 Tab키 누르기

pd.read

In [27]:
# tips2.csv 파일을 판다스의 read_csv() 함수를 활용해서 읽기
# 화면에 보이는 엑셀처럼 보이는 테이블은 데이터프레임이다.

pd.read_csv('tips2.csv')

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

### TIPS 데이터셋 가져오기

In [14]:
# tips2.csv 파일 읽고  tips2 데이터프레임에 저장합니다.

tips2 = pd.read_csv('tips2.csv')

In [29]:
# head() 함수를 통해서 tips2 데이터프레임의 앞 5개 데이터를 확인 할수 있으며
# 인덱스와 컬럼들과 value값들로 구성됩니다.

tips2.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3
3       23.68  3.31    1       0    2     1     2
4       24.59  3.61    0       0    2     1     4

![tips](https://github.com/gzone1357/Image1/raw/main/git1.png)

### 주어진 데이터프레임(테이블)에서 행과 열 접근해 값 가져오기

In [30]:
# tips2 데이터프레임(테이블) 내용 다시 확인해 봅시다.

tips2

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

### tip 컬럼의 내용만 가져와 보기

In [31]:
# 'tip' 1개의 컬럼만 가져올 경우 , 아래 화면 출력처럼 인덱스와 value값으로 구성되며
# 이런 형태를 시리즈라고 합니다.

tips2[ 'tip' ]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### tip, day, size 3개의 컬럼 내용 가져와 보기

In [32]:
# 리스트[]를 사용하여 tip, day, size 3개의 컬럼 이름을 담아
# 지정된 tip, day, size  3개의 컬럼에 대해서만 데이터를 가져옵니다.

col = [ 'tip', 'day', 'size' ]
tips2[ col ]

      tip  day  size
0    1.01    2     2
1    1.66    2     3
2    3.50    2     3
3    3.31    2     2
4    3.61    2     4
..    ...  ...   ...
239  5.92    1     3
240  2.00    1     2
241  2.00    1     2
242  1.75    1     2
243  3.00    3     2

[244 rows x 3 columns]

In [33]:
# 위에서 실행한 코드와 똑같은 결과를 만드는 코딩입니다.

tips2[ [ 'tip', 'day', 'size' ] ]

      tip  day  size
0    1.01    2     2
1    1.66    2     3
2    3.50    2     3
3    3.31    2     2
4    3.61    2     4
..    ...  ...   ...
239  5.92    1     3
240  2.00    1     2
241  2.00    1     2
242  1.75    1     2
243  3.00    3     2

[244 rows x 3 columns]

### 이번에 첫번째 행을 접근해 보자

In [34]:
# 다시 tips 데이터프레임(테이블) 내용을 살펴 보자
# 첫번째 행의 내용도 확인해 보자

tips2

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

In [35]:
# 첫번째 행(0번 라인)을 접근하기 위해 아래와 같이 0 입력 했으나 에러가 발생
# 데이터프레임에 1개의 요소를 넣으면 무조건 컬럼으로 인식하게 되어 0 이라는 컬럼을 찾게 되지만,
# 0 이라는 컬럼이 없어 에러가 발생하게 됩니다.

tips2[ 0 ]

KeyError: 0

In [36]:
# tips2 데이터프레임(테이블)에서 행들을 접근하기 위해서는 슬라이싱 필요
# 슬라이싱(0 : 1) 사용해서 첫번째 행(0번 라인)을 접근

tips2[ 0 : 1 ]

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2

### 5번째부터 9번째 행들을 출력해 보자

In [37]:
# tips2 데이터프레임(테이블)에서 행들을 접근하기 위해서는 슬라이싱 필요
# 슬라이싱(5 : 10) 사용해서 인덱스 5번부터 9번까지의 행 라인을 접근

tips2[ 5 : 10 ]

   total_bill   tip  sex  smoker  day  time  size
5       25.29  4.71    1       0    2     1     4
6        8.77  2.00    1       0    2     1     2
7       26.88  3.12    1       0    2     1     4
8       15.04  1.96    1       0    2     1     2
9       14.78  3.23    1       0    2     1     2

<br>
<br>
<br>

---

## **2. 데이터 분석**
- 데이터 값이 어떻게 되어 있으며, 어떤 흐름을 보이는지, 다른 컬럼과의 관계는 어떤지를 파악하는 거다.
- 눈으로 데이터 수치를 보고 어떤 흐름인지 파악할수 있지만,
- 시각화를 통한다면 쉽게 흐름을 파악할수 있으니, 할수 있으면 사용해라.
- 여러분에게는 어려울수 있으니, 아, 이렇게 데이터를 가지고 시각화를 할수 있구나 느낀면 된다.

### **<font color=blue>하지만, 우리는 여기서는 데이터 분석을 하지 않아요.</font>**
### **<font color=red>데이터가 이미 정제되어 있어 머신러닝과 딥러닝 모델링에 집중하도록 할게요!!</font>**

<br>
<br>
<br>

---

## **3. [회귀모델 ] X, y 나누기**
- 지도학습 경우 데이터와 정답이 있어야 합니다.
- 데이터에 해당하는 X와 정답에 해당하는 y가 있어야 합니다.
- 아래와 같이 판다스를 이용하면 X, y를 쉽게 나눌수 있어요.
- X, y 데이터를 가지고 모델 학습하고 검증할수 있는 학습 데이터셋과 테스트 데이터셋으로 나눠 사용합니다.
- 그리고 레이블(y) 값을 보고 회귀 모델인지, 분류 모델인지 구별할수 있어요
  - 레이블(y) : 학점 A/B/C/DF , 남녀 남/여, 숫자 0~9 --> 범주형으로 되어 있으면 분류 모델
  - 레이블(y) : 삼성전자 주가, 습도/온도, 유가동향 등 --> 연속형으로 되어 있으면 회귀 모델

### **<font color=blue>우리는 회귀 모델을 만들어야 하는데, 어떤 컬럼을 정답(레이블, y)를 정할까요?</font>**
### **<font color=blue>회귀모델 위해서 연속형 컬럼을 레이블(y)로 선택해야 합니다.</font>**

In [38]:
# tips2 데이터프레임의 뒤 5개 행 라인 보기
# 연속적인 값들이 있는 컬럼은 무엇이 있나요?

tips2.tail()

     total_bill   tip  sex  smoker  day  time  size
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

### **<font color=blue>연속적인 값을 나타내는 컬럼이 total_bill, tip 컬럼들이 있네요</font>**

In [39]:
# 다시 한번 tips2 내용을 보겠습니다.

tips2.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3

### **그중에서 정답(레이블, y)을 tip 컬럼으로 정했고, tip의 값들이 연속적인 값이니 <font color=blue>회귀 모델</font>이 되겠네요.**

In [40]:
# tips2 데이터프레임(테이블)에서 tip 컬럼만 제외하면 나머지가 X가 되겠네요.
# tips 컬럼을 제외하고 나머지 컬럼들을 일일히 리스트에 나열해 조회해 보겠습니다.

tips2[['total_bill', 'sex', 'smoker', 'day', 'time', 'size']]

     total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     1     2
1         10.34    1       0    2     1     3
2         21.01    1       0    2     1     3
3         23.68    1       0    2     1     2
4         24.59    0       0    2     1     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     1     3
240       27.18    0       1    1     1     2
241       22.67    1       1    1     1     2
242       17.82    1       0    1     1     2
243       18.78    0       0    3     1     2

[244 rows x 6 columns]

In [41]:
# 레이블(y)는 tips2 데이터프레임(테이블)에서 tip 컬럼만 가져오면 되겠네요.
# 출력 결과는 인덱스와 value값으로 이루어진 시리즈 형태입니다.

tips2['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### **<font color=blue>판다스의 drop 함수를 이용하면 쉽게 X, y를 나눌수 있어요!!</font>**

In [11]:
# ? 활용하여 도움말 보기
tips2.drop?

Signature:
tips2.drop(
    labels: 'IndexLabel | ListLike' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | ListLike' = None,
    columns: 'IndexLabel | ListLike' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise',
) -> 'DataFrame | None'
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by directly specifying index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level. See the :ref:`user guide <advanced.shown_levels>`
for more information about the now unused levels.

Parameters
----------
labels : single label or iterable of labels
    Index or column labels to drop. A tuple will be used as a single
    label and not treated as an iterable.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or iterable of labels
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).
columns : single label or iterable of labels
    Alternative to specifying axis (``labels, axis=1``
    is equivalent to ``columns=labels``).
level : int or level name, optional
    For MultiIndex, level from which the labels will be removed.
inplace : bool, default False
    If False, return a copy. Otherwise, do operation
    in place and return None.
errors : {'ignore', 'raise'}, default 'raise'
    If 'ignore', suppress error and only existing labels are
    dropped.

Returns
-------
DataFrame or None
    Returns DataFrame or None DataFrame with the specified
    index or column labels removed or None if inplace=True.

Raises
------
KeyError
    If any of the labels is not found in the selected axis.

See Also
--------
DataFrame.loc : Label-location based indexer for selection by label.
DataFrame.dropna : Return DataFrame with labels on given axis omitted
    where (all or any) data are missing.
DataFrame.drop_duplicates : Return DataFrame with duplicate rows
    removed, optionally only considering certain columns.
Series.drop : Return Series with specified index labels removed.

Examples
--------
>>> df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=["A", "B", "C", "D"])
>>> df
   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

Drop columns

>>> df.drop(["B", "C"], axis=1)
   A   D
0  0   3
1  4   7
2  8  11

>>> df.drop(columns=["B", "C"])
   A   D
0  0   3
1  4   7
2  8  11

Drop a row by index

>>> df.drop([0, 1])
   A  B   C   D
2  8  9  10  11

Drop columns and/or rows of MultiIndex DataFrame

>>> midx = pd.MultiIndex(
...     levels=[["llama", "cow", "falcon"], ["speed", "weight", "length"]],
...     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
... )
>>> df = pd.DataFrame(
...     index=midx,
...     columns=["big", "small"],
...     data=[
...         [45, 30],
...         [200, 100],
...         [1.5, 1],
...         [30, 20],
...         [250, 150],
...         [1.5, 0.8],
...         [320, 250],
...         [1, 0.8],
...         [0.3, 0.2],
...     ],
... )
>>> df
                big     small
llama   speed   45.0    30.0
        weight  200.0   100.0
        length  1.5     1.0
cow     speed   30.0    20.0
        weight  250.0   150.0
        length  1.5     0.8
falcon  speed   320.0   250.0
        weight  1.0     0.8
        length  0.3     0.2

Drop a specific index combination from the MultiIndex
DataFrame, i.e., drop the combination ``'falcon'`` and
``'weight'``, which deletes only the corresponding row

>>> df.drop(index=("falcon", "weight"))
                big     small
llama   speed   45.0    30.0
        weight  200.0   100.0
        length  1.5     1.0
cow     speed   30.0    20.0
        weight  250.0   150.0
        length  1.5     0.8
falcon  speed   320.0   250.0
        length  0.3     0.2

>>> df.drop(index="cow", columns="small")
                big
llama   speed   45.0
        weight  200.0
        length  1.5
falcon  speed   320.0
        weight  1.0
        length  0.3

>>> df.drop(index="length", level=1)
                big     small
llama   speed   45.0    30.0
        weight  200.0   100.0
cow     speed   30.0    20.0
        weight  250.0   150.0
falcon  speed   320.0   250.0
        weight  1.0     0.8
File:      ~/Documents/01_career/02_certificate/.venv/lib/python3.14/site-packages/pandas/core/frame.py
Type:      method

In [42]:
# Tab 키를 이용해서 자동 완성 황용하기
tips2.dro

AttributeError: 'DataFrame' object has no attribute 'dro'

In [16]:
# X 데이터 분리 : 판다스 drop 함수 활용
# 입력 : 'tip', axis=1

X = tips2.drop('tip', axis=1)

In [44]:
# 분리된 X 데이터 확인 : 데이터 타입이 데이터프레임 확인
# 레이블 tip 컬럼은 보이지 않음을 확인할수 있습니다.

X

     total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     1     2
1         10.34    1       0    2     1     3
2         21.01    1       0    2     1     3
3         23.68    1       0    2     1     2
4         24.59    0       0    2     1     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     1     3
240       27.18    0       1    1     1     2
241       22.67    1       1    1     1     2
242       17.82    1       0    1     1     2
243       18.78    0       0    3     1     2

[244 rows x 6 columns]

In [17]:
# y 데이터 분리 : 'tip' 컬럼값만 분리해서 가져오면 됨.

y = tips2['tip']

In [46]:
# 분리된 y 데이터 확인 : 데이터 타입이 Series 확인
# y 값이 실수형으로 되어 있음 확인

y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### **X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 볼게요.**

In [18]:
# X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 주는 train_test_split 함수가 있습니다.
# train_test_split 함수를 이용하면 쉽게 학습 데이터셋과 테스트 데이터셋 만들수 있습니다.
# 사이킷런의 train_test_split 함수 불러 옵니다.

from sklearn.model_selection import train_test_split

In [48]:
# ? 활용하여 도움말 보기
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...

>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
File:      ~/Documents/01_career/02_certificate/.venv/lib/python3.14/site-packages/sklearn/model_selection/_split.py
Type:      function

In [19]:
# train_test_split 함수
# 1. X ,y 입력
# 2. test_size=0.2 --> train set : test set  = 8 : 2
# 3. random_state 사용하지 않으면 실행할때마다 학습셋과 테스트셋이 다르게 나와 고정하기 위해 사용
# 4. train_test_split 함수 결과로 X_train, X_test, y_train, y_test 나옴.

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

In [50]:
# 학습 데이터셋과 테스트 데이터셋의 사이즈 확인

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [20]:
# 뒤쪽에서 사용하게 편하게 데이터프레임을 넘파이(numpy)로 변경합니다.

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

<br>
<br>
<br>

---

# **머신러닝 모델 포맷**

![머신러닝 포맷](https://github.com/gzone1357/Image1/raw/main/git2.png)

<br>
<br>
<br>

---

## **4. (회귀) 머신러닝 모델링**
- DecisionTree 결정트리
- RandomForest 앙상블

### DecisionTree

![결정트리](https://github.com/gzone1357/Image1/raw/main/tree-depth-2.png)

In [ ]:
# 외우면 좋지만, 다 외울수 없기에
# Tab 키를 활용해서 자동완성 사용하자.
# 그리고 레이블(y)값을 tips로 정햇으니, 연속적인 값들이므로 회귀 모델입니다.
# 회귀 모델을 선택해야 합니다.

from sklearn.tree import De

In [6]:
# DecisionTree 머신러닝 모델링

from sklearn.tree import DecisionTreeRegressor

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기
DecisionTreeRegressor?

In [21]:
# 1. DecisionTreeRegressor 모델 정의 -> dtr 저장
# 2. dtr 모델 학습 : X_train, y_train
# 3. dtr 모델 성능확인 : X_test, y_test

dtr = DecisionTreeRegressor()
dtr.fit(  X_train, y_train  )
dtr.score(  X_test, y_test  )

-0.10806458470418234

### RandomForest

![RandomForest](https://github.com/gzone1357/Image1/raw/main/rf.png)

In [54]:
# RandomForest 머신러닝 모델링

from sklearn.ensemble import RandomForestRegressor

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기

RandomForestRegressor

sklearn.ensemble._forest.RandomForestRegressor

### RandomForestRegressor 모델 생성시 트리의 갯수 50, 트리의 깊이 6 <font color='blue'>하이퍼 파라미터</font> 넣어보자!!

In [55]:
# 1. RandomForestRegressor 모델 정의 : 트리의 갯수 50, 트리의 깊이 6 -> rfr 저장
# 2. rfr 모델 학습 : X_train, y_train
# 3. rfr 모델 성능확인 : X_test, y_test

rfr = RandomForestRegressor( n_estimators=50, max_depth=6 )
rfr.fit(  X_train, y_train  )
rfr.score(  X_test, y_test  )

0.2458571032971355

In [56]:
# 만든 RandomForest 모델의 성능이 잘 나오는지 확인하기 전에 테스트셋의 첫번째 데이터와 정답 확인

X_test[0], y_test[0]

(array([19.82,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ]), np.float64(3.18))

In [57]:
# 테스트셋의 0 라인 샘플 데이터을 모델 입력해서 예측하기
# rfr 모델의 predict 함수 활용
# 입력 : [X_test[0]], 결과 : pred 저장
# pred 결과 출력

pred = rfr.predict([X_test[0]])
print(pred)

[2.91016528]

<br>
<br>
<br>

---

## **5. [분류모델 ] X, y 나누기**
- 지도학습 경우 데이터와 정답이 있어야 합니다.
- 데이터에 해당하는 X와 정답에 해당하는 y가 있어야 합니다.
- 아래와 같이 판다스를 이용하면 X, y를 쉽게 나눌수 있어요.
- X, y 데이터를 가지고 모델 학습하고 검증할수 있는 학습 데이터셋과 테스트 데이터셋으로 나눠 사용합니다.
- 그리고 레이블(y) 값을 보고 회귀 모델인지, 분류 모델인지 구별할수 있어요.
  - 레이블(y) : 학점 A/B/C/DF , 남녀 남/여, 숫자 0~9 --> 범주형으로 되어 있으면 분류 모델
  - 레이블(y) : 삼성전자 주가, 습도/온도, 유가동향 등 --> 연속형으로 되어 있으면 회귀 모델

### **<font color=blue>우리는 분류 모델을 해야 되는데, 어떤 컬럼을 정답(레이블, y)를 정할까요?</font>**
### **<font color=blue>분류모델 위해서 범주형 컬럼을 레이블(y)로 선택해야 합니다.</font>**

In [58]:
# tips2 데이터프레임의 뒤 5개 행 라인 보기
# 범주형 값들이 있는 컬럼은 무엇이 있나요?

tips2.tail()

     total_bill   tip  sex  smoker  day  time  size
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

### **<font color=blue>범주형 값을 나타내는 컬럼이 sex, smoker, day, time, size 컬럼들이 있네요</font>**

In [59]:
# 다시 한번 tips2 내용을 보겠습니다.

tips2.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3

### **그중에서 정답(레이블, y)을 smoker 컬럼으로 정했고, smoker의 값들이 범주형 값이니 <font color=blue>분류 모델</font>이 되겠네요.**

In [60]:
# tips2 테이블에서 smoker 컬럼만 제외하면 나머지가 X가 되겠네요.
# smoker 컬럼만 제외한 나머지 컬럼 ['total_bill', 'tip', 'sex', 'day', 'time', 'size'] 조회해 봅시다.

tips2[ ['total_bill', 'tip', 'sex', 'day', 'time', 'size'] ]

     total_bill   tip  sex  day  time  size
0         16.99  1.01    0    2     1     2
1         10.34  1.66    1    2     1     3
2         21.01  3.50    1    2     1     3
3         23.68  3.31    1    2     1     2
4         24.59  3.61    0    2     1     4
..          ...   ...  ...  ...   ...   ...
239       29.03  5.92    1    1     1     3
240       27.18  2.00    0    1     1     2
241       22.67  2.00    1    1     1     2
242       17.82  1.75    1    1     1     2
243       18.78  3.00    0    3     1     2

[244 rows x 6 columns]

In [61]:
# 레이블(y)는 tips2 테이블에서 smoker 컬럼만 가져오면 되겠네요.

tips2['smoker']

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: smoker, Length: 244, dtype: int64

### **<font color=blue>판다스의 drop 함수를 이용하면 쉽게 X, y를 나눌수 있어요!!</font>**

In [ ]:
# ? 활용하여 도움말 보기

tips2.drop?

In [ ]:
# Tab 키를 이용해서 자동 완성 황용하기

tips2.dro

In [62]:
# X 데이터 분리 : 판다스 drop 함수 활용
# 입력 : 'smoker', axis=1

X = tips2.drop('smoker', axis=1)

In [63]:
# 분리된 X 데이터 확인 : 출력결과가  데이터프레임 확인할수 있음.
# 레이블 smoker 컬럼은 보이지 않음을 확인할수 있습니다.

X

     total_bill   tip  sex  day  time  size
0         16.99  1.01    0    2     1     2
1         10.34  1.66    1    2     1     3
2         21.01  3.50    1    2     1     3
3         23.68  3.31    1    2     1     2
4         24.59  3.61    0    2     1     4
..          ...   ...  ...  ...   ...   ...
239       29.03  5.92    1    1     1     3
240       27.18  2.00    0    1     1     2
241       22.67  2.00    1    1     1     2
242       17.82  1.75    1    1     1     2
243       18.78  3.00    0    3     1     2

[244 rows x 6 columns]

In [64]:
# y 데이터 분리 : 'smoker' 컬럼값만 분리

y = tips2['smoker']

In [65]:
# 분리된 y 데이터 확인 : 데이터 타입이 Series 확인
# y 값이 정수 0과1의 범주형으로 되어 있음 확인

y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: smoker, Length: 244, dtype: int64

### **X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 볼게요.**

In [66]:
# X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 주는 train_test_split 함수가 있습니다.
# train_test_split 함수를 이용하면 쉽게 학습 데이터셋과 테스트 데이터셋 만들수 있습니다.
# 사이킷런의 train_test_split 함수 불러 옵니다.

from sklearn.model_selection import train_test_split

In [ ]:
# ? 활용하여 도움말 보기
train_test_split?

In [67]:
# train_test_split 함수
# 1. X ,y 입력
# 2. test_size=0.2 --> train set : test set  = 8 : 2
# 3. random_state 사용하지 않으면 실행할때마다 학습셋과 테스트셋이 다르게 나와 고정하기 위해 사용
# 4. train_test_split 함수 결과로 X_train, X_test, y_train, y_test 나옴.

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

In [68]:
# 학습 데이터셋과 테스트 데이터셋의 사이즈 확인

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [69]:
# 뒤쪽에서 사용하게 편하게 데이터프레임을 넘파이(numpy)로 변경합니다.

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

<br>
<br>
<br>

---

## **6. (분류) 머신러닝 모델링**
- DecisionTree 결정트리
- RandomForest 앙상블

### DecisionTree

![결정트리](https://github.com/gzone1357/Image1/raw/main/tree-depth-2.png)

In [ ]:
# 외우면 좋지만, 다 외울수 없기에
# Tab 키를 활용해서 자동완성 사용하자.
# 그리고 레이블(y)값을 smoker로 정햇으니, 범주형 값들이므로 분류 모델입니다.
# 회귀 모델을 선택해야 합니다.

from sklearn.tree import De

In [70]:
# DecisionTree 머신러닝 모델링
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기
DecisionTreeClassifier?

In [71]:
# 1. DecisionTreeClassifier 모델 정의 -> dtc 저장
# 2. dtc 모델 학습 : X_train, y_train
# 3. dtc 모델 성능확인 : X_test, y_test

dtc = DecisionTreeClassifier()
dtc.fit( X_train, y_train )
dtc.score( X_test, y_test )

0.673469387755102

### RandomForest

![RandomForest](https://github.com/gzone1357/Image1/raw/main/rf.png)

In [72]:
# RandomForest 머신러닝 모델링
from sklearn.ensemble import RandomForestClassifier

In [73]:
# ? , shift+Tab 활용하여 도움말 보기
RandomForestClassifier

sklearn.ensemble._forest.RandomForestClassifier

In [76]:
# 1. RandomForestClassifier 모델 정의 -> rfc 저장
# 2. rfc 모델 학습 : X_train, y_train
# 3. rfc 모델 성능확인 : X_test, y_test

rfc = RandomForestClassifier()
rfc.fit( X_train, y_train )
rfc.score( X_test, y_test )

0.673469387755102

In [77]:
# 테스테셋의 0 라인 샘플 데이터와 정답 확인

X_test[0], y_test[0]

(array([19.82,  3.18,  1.  ,  1.  ,  1.  ,  2.  ]), np.int64(0))

In [78]:
# 테스테셋의 0 라인 샘플 데이터을 모델 입력해서 예측하기
# rfc 모델의 predict 함수 활용
# 입력 : [X[0]], 결과 : pred 저장
# pred 결과 출력

pred = rfc.predict([X_test[0]])
print(pred)

[0]

<br>
<br>
<br>

# **[실습] 머신러닝 모델링하기**

**아래 가이드에 따라 tips 데이터프레임을 활용하여 머신러닝 모델을 만드세요.**

- **회귀 모델 만들기**
  - 대상 데이터 : tips 데이터프레임
  - X, y 데이터 만들기
    - y 레이블 : total_bill
    - x 퓨쳐 : total_bill 제외한 나머지
  - train_test_split 함수를 활용해서 학습 데이터셋과 테스트 데이터셋을 만드세요.
    - 학습데이터셋 : 테스트데이터셋 = 8 : 2
    - random_state : 41  
  - KNN 모델을 만들고 학습하세요.
  - 만든 KNN 모델을 활용해서 아래 시뮬레이션 데이터에 대한 예측하세요.
    - 시뮬레이션 데이터 :  [3.23, 1.  , 0.  , 2.  , 1.  , 2.  ]

- **분류 모델 만들기**
  - 대상 데이터 : tips 데이터프레임
  - X, y 데이터 만들기
    - y 레이블 : day
    - x 퓨쳐 : day 제외한 나머지
  - train_test_split 함수를 활용해서 학습 데이터셋과 테스트 데이터셋을 만드세요.
    - 학습데이터셋 : 테스트데이터셋 = 8 : 2
    - random_state : 41  
  - KNN 모델을 만들고 학습하세요.
  - 만든 KNN 모델을 활용해서 아래 시뮬레이션 데이터에 대한 예측하세요.
    - 시뮬레이션 데이터 :  [14.78,  3.23,  1.  ,  0.  ,  1.  ,  2.  ]

**회귀 KNN 머신러닝 모델**

In [79]:
# X, y 나누기
X = tips.drop('total_bill', axis=1)
y = tips[ 'total_bill' ]

In [80]:
# 학습 데이터셋과 테스트 데이터셋 나누기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=41 )
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [81]:
# KNeighborsRegressor 모델 학습
# n_neighbors 이웃갯수 : 3

from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [82]:
# KNN 모델을 활용해서 시뮬레이션 데이터 예측하기

simul = [3.23, 1. , 0. , 2. , 1. , 2. ]
knn.predict([ simul ])

array([20.00333333])

<br>

**분류 KNN 머신러닝 모델**

In [83]:
# X, y 나누기
X = tips.drop('day', axis=1)
y = tips[ 'day' ]

In [84]:
# 학습 데이터셋과 테스트 데이터셋 나누기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=41 )
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [85]:
# KNeighborsClassifier 모델 학습
# n_neighbors 이웃갯수 : 3

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [86]:
# KNN 모델을 활용해서 시뮬레이션 데이터 예측하기

simul = [14.78,  3.23,  1.  ,  0.  ,  1.  ,  2.  ]
knn.predict([ simul ])

array([1])

---

# 정리

**Tips 데이터 활용하여 쉽게 모델링하기**
- 간단하게 쉽게 머신러닝 모델링 만들어 보기
- 원하는 컬럼을 선택해서 회귀 모델, 분류 모델 만들어 보기
- 잘 몰라도 아래 순서에 맞게, 이런 식으로 실행하면 되겠구나 느끼기
- 여러분이 처음 한다고 생각하고 템플릿 작성함.

**모델링 프로세스 확인하기**
1. 데이터 가져오기
2. 데이터 분석
3. X, y 나누기
4. 머신러닝 모델링