In [ ]:
# 데이터 로드
import seaborn as sns

row_tips = sns.load_dataset('tips')

In [ ]:
# 데이터 전처리 및 저장 

## 1. 데이터 탐색
    # sex, smoker, time 컬럼이 (str, object가 아닌) category임을 확인.
    # replace 대신 map 사용해야 에러 없음.
row_tips.dtypes

## 2. 데이터 변경 (기존 문자열 데이터를 숫자형 데이터로 변경)
row_tips['sex'] = row_tips['sex'].map({'Female':0, 'Male':1})
row_tips['smoker'] = row_tips['smoker'].map({'No':0, 'Yes':1})
row_tips['time'] = row_tips['time'].map({'Lunch':0, 'Dinner':1})

## 3. Feature Engineering
    # 요일 칼럼을 문자열에서 숫자열로 변경
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
row_tips['day'] = le.fit_transform(row_tips['day'])

## 4. 변형된 데이터 저장
row_tips.to_csv('tips2.csv', index=False)

In [ ]:
# 변형 데이터 호출
import pandas as pd

tips = pd.read_csv('tips2.csv')

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

In [ ]:
# 데이터 탐색

tips['tip'] # 단일 컬럼의 데이터에 접근
tips[['tip', 'day', 'size']] # 복합 컬럼의 데이터에 접근
tips[0:1] # 단일 행의 데이터에 접근. 첫 번째 행에 접근. [0] 아님
tips[5:10] # 복합 행의 데이터에 접근. 5~9까지 행에 접근.

   total_bill   tip sex smoker  day time  size
5       25.29  4.71   1      0    2    1     4
6        8.77  2.00   1      0    2    1     2
7       26.88  3.12   1      0    2    1     4
8       15.04  1.96   1      0    2    1     2
9       14.78  3.23   1      0    2    1     2

In [10]:
# 데이터 분석(생략)

In [ ]:
# 머신러닝 모델링 - 학습 데이터, 평가 데이터 구분하기
    # 지도학습의 경우, 정답 필요
    # x, y 데이터를 갖고 모델 학습하고 검증할 수 있는 학습 및 평가 데이터셋으로 구분 필요
    # y(레이블) 값으로 회귀, 분류 구별 가능
        # 예시: 학점, 남녀, 1~9 등급 등 -> 범주형 데이터이므로 분류 모델
        # 예시: 삼성전자 주가, 습도/온도, 유가 동향 등 -> 연속형 데이터이므로 회귀 모델

# "회귀 모델"로 가정
    # 연속형 데이터 탐색하기
# tips.info() # total_bill, tip 컬럼의 경우 연속형 데이터임을 확인.

# x, y 데이터 설정
y = tips[['tip']] # 이 중 tip을 y로 선택.
x = tips.drop(columns='tip') # 그 외 나머지 컬럼은 x로 선택

# x, y로 학습 및 평가 데이터셋 만들기
    # 학습 : 평가 = 8 : 2
    # 재현 가능함을 고려하도록 값을 고정
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

# 사용의 효율성을 위해 재할당 (데이터프레임을 넘파이(numpy)로 변경)
x_train = x_train.values
x_test = x_test.values
y_train = y_train.values
y_test = y_test.values

x_train, x_test, y_train, y_test

(array([[13.28,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [24.27,  1.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [27.28,  1.  ,  1.  ,  0.  ,  1.  ,  2.  ],
        ...,
        [ 5.75,  0.  ,  1.  ,  0.  ,  1.  ,  2.  ],
        [34.63,  1.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [44.3 ,  0.  ,  1.  ,  1.  ,  1.  ,  3.  ]]),
 array([[19.82,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [ 8.77,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [24.55,  1.  ,  0.  ,  2.  ,  1.  ,  4.  ],
        [25.89,  1.  ,  1.  ,  1.  ,  1.  ,  4.  ],
        [13.  ,  0.  ,  1.  ,  3.  ,  0.  ,  2.  ],
        [17.89,  1.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [28.44,  1.  ,  1.  ,  3.  ,  0.  ,  2.  ],
        [12.48,  0.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [14.78,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [15.38,  0.  ,  1.  ,  0.  ,  1.  ,  2.  ],
        [18.29,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [10.77,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [10.65,  0.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [14.48,  1.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [10.07,  0.  ,  0.  ,  3.  ,  0.  ,  1.  ],
        [18.64,  0.  ,  0.  ,  3.  ,  0.  ,  3.  ],
        [18.71,  1.  ,  1.  ,  3.  ,  0.  ,  3.  ],
        [21.58,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [16.45,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [41.19,  1.  ,  0.  ,  3.  ,  0.  ,  5.  ],
        [20.69,  0.  ,  0.  ,  1.  ,  1.  ,  4.  ],
        [20.65,  1.  ,  0.  ,  1.  ,  1.  ,  3.  ],
        [14.31,  0.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [ 9.55,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [20.9 ,  0.  ,  1.  ,  2.  ,  1.  ,  3.  ],
        [11.69,  1.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [10.27,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [25.28,  0.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [16.49,  1.  ,  0.  ,  2.  ,  1.  ,  4.  ],
        [48.17,  1.  ,  0.  ,  2.  ,  1.  ,  6.  ],
        [38.07,  1.  ,  0.  ,  2.  ,  1.  ,  3.  ],
        [ 7.74,  1.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [17.81,  1.  ,  0.  ,  1.  ,  1.  ,  4.  ],
        [20.29,  1.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [16.97,  0.  ,  0.  ,  2.  ,  1.  ,  3.  ],
        [24.08,  0.  ,  0.  ,  3.  ,  0.  ,  4.  ],
        [12.03,  1.  ,  1.  ,  0.  ,  1.  ,  2.  ],
        [43.11,  0.  ,  1.  ,  3.  ,  0.  ,  4.  ],
        [13.16,  0.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [22.67,  1.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [10.51,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [14.52,  0.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [23.95,  1.  ,  0.  ,  2.  ,  1.  ,  2.  ],
        [10.33,  0.  ,  0.  ,  2.  ,  1.  ,  3.  ],
        [10.34,  1.  ,  1.  ,  3.  ,  0.  ,  2.  ],
        [ 3.07,  0.  ,  1.  ,  1.  ,  1.  ,  1.  ],
        [10.59,  0.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [18.69,  1.  ,  0.  ,  1.  ,  1.  ,  3.  ],
        [ 7.56,  1.  ,  0.  ,  3.  ,  0.  ,  2.  ]]),
 array([[ 2.72],
        [ 2.03],
        [ 4.  ],
        [ 4.5 ],
        [ 2.03],
        [ 3.51],
        [ 2.  ],
        [ 5.15],
        [ 1.75],
        [ 2.74],
        [ 3.  ],
        [ 5.14],
        [ 3.5 ],
        [ 5.65],
        [ 2.5 ],
        [ 2.01],
        [ 4.08],
        [ 2.09],
        [ 1.  ],
        [ 3.41],
        [ 3.48],
        [ 2.  ],
        [ 3.  ],
        [ 2.71],
        [ 3.  ],
        [ 3.  ],
        [ 3.  ],
        [ 3.68],
        [ 4.71],
        [ 3.  ],
        [ 4.2 ],
        [ 1.73],
        [ 4.  ],
        [ 3.15],
        [ 1.5 ],
        [ 3.  ],
        [ 2.  ],
        [ 2.5 ],
        [ 1.57],
        [ 3.6 ],
        [ 4.3 ],
        [ 3.06],
        [ 5.92],
        [ 1.48],
        [ 4.3 ],
        [ 3.  ],
        [ 2.6 ],
        [ 4.73],
        [ 3.5 ],
        [ 4.  ],
        [ 3.08],
        [ 2.54],
        [ 3.76],
        [ 3.  ],
        [ 3.  ],
        [ 2.3 ],
        [ 2.  ],
        [ 1.25],
        [ 2.5 ],
        [ 6.5 ],
        [ 2.02],
        [ 1.01],
        [ 3.5 ],
        [ 4.  ],
        [ 5.  ],
        [ 2.5 ],
        [ 2.  ],
        [ 1.63],
        [ 3.11],
        [ 3.  ],
        [ 5.17],
        [10.  ],
        [ 2.5 ],
        [ 3.  ],
        [ 2.  ],
        [ 5.  ],
        [ 2.  ],
        [ 2.23],
        [ 1.8 ],
        [ 2.61],
        [ 2.  ],
        [ 5.  ],
        [ 4.67],
        [ 2.  ],
        [ 2.5 ],
        [ 3.61],
        [ 2.5 ],
        [ 3.  ],
        [ 6.7 ],
        [ 3.18],
        [ 2.  ],
        [ 1.98],
        [ 1.25],
        [ 2.  ],
        [ 2.2 ],
        [ 3.  ],
        [ 1.97],
        [ 3.23],
        [ 2.64],
        [ 5.6 ],
        [ 3.09],
        [ 2.24],
        [ 2.  ],
        [ 7.58],
        [ 3.5 ],
        [ 4.  ],
        [ 3.4 ],
        [ 5.  ],
        [ 4.  ],
        [ 6.  ],
        [ 3.25],
        [ 5.  ],
        [ 1.32],
        [ 1.5 ],
        [ 1.5 ],
        [ 3.31],
        [ 1.64],
        [ 1.56],
        [ 2.  ],
        [ 3.48],
        [ 1.17],
        [ 2.  ],
        [ 3.  ],
        [ 2.  ],
        [ 3.  ],
        [ 3.27],
        [ 2.01],
        [ 3.12],
        [ 3.16],
        [ 3.  ],
        [ 3.5 ],
        [ 5.  ],
        [ 1.5 ],
        [ 1.92],
        [ 3.  ],
        [ 1.96],
        [ 3.  ],
        [ 6.73],
        [ 2.23],
        [ 2.83],
        [ 3.71],
        [ 2.24],
        [ 3.14],
        [ 3.39],
        [ 3.25],
        [ 2.  ],
        [ 1.58],
        [ 3.76],
        [ 4.34],
        [ 4.29],
        [ 2.5 ],
        [ 2.  ],
        [ 4.  ],
        [ 9.  ],
        [ 4.  ],
        [ 2.  ],
        [ 1.1 ],
        [ 2.  ],
        [ 1.76],
        [ 2.05],
        [ 5.85],
        [ 2.75],
        [ 1.5 ],
        [ 2.5 ],
        [ 3.5 ],
        [ 1.  ],
        [ 2.  ],
        [ 4.19],
        [ 2.18],
        [ 3.07],
        [ 3.75],
        [ 2.88],
        [ 1.66],
        [ 5.2 ],
        [ 2.  ],
        [ 1.5 ],
        [ 2.  ],
        [ 3.48],
        [ 1.5 ],
        [ 5.07],
        [ 4.  ],
        [ 2.  ],
        [ 2.2 ],
        [ 6.5 ],
        [ 2.  ],
        [ 1.68],
        [ 3.  ],
        [ 4.08],
        [ 3.5 ],
        [ 3.  ],
        [ 4.06],
        [ 3.02],
        [ 1.  ],
        [ 3.55],
        [ 2.5 ]]),
 array([[3.18],
        [2.  ],
        [2.  ],
        [5.16],
        [2.  ],
        [2.  ],
        [2.56],
        [2.52],
        [3.23],
        [3.  ],
        [3.  ],
        [1.47],
        [1.5 ],
        [2.  ],
        [1.83],
        [1.36],
        [4.  ],
        [3.92],
        [2.47],
        [5.  ],
        [2.45],
        [3.35],
        [4.  ],
        [1.45],
        [3.5 ],
        [2.31],
        [1.71],
        [5.  ],
        [2.  ],
        [5.  ],
        [4.  ],
        [1.44],
        [2.34],
        [3.21],
        [3.5 ],
        [2.92],
        [1.5 ],
        [5.  ],
        [2.75],
        [2.  ],
        [1.25],
        [2.  ],
        [2.55],
        [1.67],
        [2.  ],
        [1.  ],
        [1.61],
        [2.31],
        [1.44]]))

In [ ]:
# 머신러닝 모델링 - 머신러닝 모델링
    # 회귀이므로, Regressor 사용
    # 예시: Linear, KNN, DecisionTree, RandomForest

## 1. Linear
## 2. KNN

## 3. DecisionTree
# from sklearn.tree import DecisionTreeRegressor
# dtr = DecisionTreeRegressor(max_depth=5)
# dtr.fit(x_train, y_train) # 학습 실행
# dtr.score(x_test, y_test) # 모델의 성능 점수 계산 (R^2 Score)
# 결과: -0.05633768464230027. 모델이 평균값보다 못한 예측을 하고 있다는 의미. 학습이 제대로 되지 않음을 의미.
# 시사: max_depth을 5, 10, 15 등으로 조정해보기, 더 강력한 모델로 바꾸기

## 4. RandomForest
    # tree 개수 50, 깊이 6으로 설정 -> 하이퍼 파라미터 조정
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=50, max_depth=6)
rfr.fit(x_train, y_train.ravel()) # .ravel()로 2차원 백터를 1차원으로 변경. Warning 메시지 해결
rfr.score(x_test, y_test.ravel())

# 결과 확인
x_test[0], y_test[0] # 테스트셋의 첫 번째 데이터와 정답 확인
pred = rfr.predict([x_test[0]]) # 만든 RandomForest 모델의 성능이 잘 나오는지 확인
print(pred)

[3.03091516]

In [74]:
# 머신러닝 모델링 - 학습 데이터, 평가 데이터 구분하기
    # 지도학습의 경우, 정답 필요
    # x, y 데이터를 갖고 모델 학습하고 검증할 수 있는 학습 및 평가 데이터셋으로 구분 필요
    # y(레이블) 값으로 회귀, 분류 구별 가능
        # 예시: 학점, 남녀, 1~9 등급 등 -> 범주형 데이터이므로 분류 모델
        # 예시: 삼성전자 주가, 습도/온도, 유가 동향 등 -> 연속형 데이터이므로 회귀 모델

# "분류 모델"로 가정
    # 범주형 데이터 탐색하기
tips.info() # sex, smoker, day, time, size 컬럼의 경우 범주형 데이터임을 확인.

# x, y 데이터 설정
y = tips[['smoker']] # 이 중 smoker을 y로 선택.
x = tips.drop(columns='smoker') # 그 외 나머지 컬럼은 x로 선택

# x, y로 학습 및 평가 데이터셋 만들기
    # 학습 : 평가 = 8 : 2
    # 재현 가능함을 고려하도록 값을 고정
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

# 사용의 효율성을 위해 재할당 (데이터프레임을 넘파이(numpy)로 변경)
x_train = x_train.values
x_test = x_test.values
y_train = y_train.values
y_test = y_test.values

x_train, x_test, y_train, y_test

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    int64
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(3), float64(2), int64(2)
memory usage: 8.6 KB

(array([[13.28,  2.72,  1.  ,  1.  ,  1.  ,  2.  ],
        [24.27,  2.03,  1.  ,  1.  ,  1.  ,  2.  ],
        [27.28,  4.  ,  1.  ,  0.  ,  1.  ,  2.  ],
        ...,
        [ 5.75,  1.  ,  0.  ,  0.  ,  1.  ,  2.  ],
        [34.63,  3.55,  1.  ,  2.  ,  1.  ,  2.  ],
        [44.3 ,  2.5 ,  0.  ,  1.  ,  1.  ,  3.  ]]),
 array([[19.82,  3.18,  1.  ,  1.  ,  1.  ,  2.  ],
        [ 8.77,  2.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [24.55,  2.  ,  1.  ,  2.  ,  1.  ,  4.  ],
        [25.89,  5.16,  1.  ,  1.  ,  1.  ,  4.  ],
        [13.  ,  2.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [17.89,  2.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [28.44,  2.56,  1.  ,  3.  ,  0.  ,  2.  ],
        [12.48,  2.52,  0.  ,  3.  ,  0.  ,  2.  ],
        [14.78,  3.23,  1.  ,  2.  ,  1.  ,  2.  ],
        [15.38,  3.  ,  0.  ,  0.  ,  1.  ,  2.  ],
        [18.29,  3.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [10.77,  1.47,  1.  ,  1.  ,  1.  ,  2.  ],
        [10.65,  1.5 ,  0.  ,  3.  ,  0.  ,  2.  ],
        [14.48,  2.  ,  1.  ,  2.  ,  1.  ,  2.  ],
        [10.07,  1.83,  0.  ,  3.  ,  0.  ,  1.  ],
        [18.64,  1.36,  0.  ,  3.  ,  0.  ,  3.  ],
        [18.71,  4.  ,  1.  ,  3.  ,  0.  ,  3.  ],
        [21.58,  3.92,  1.  ,  2.  ,  1.  ,  2.  ],
        [16.45,  2.47,  0.  ,  1.  ,  1.  ,  2.  ],
        [41.19,  5.  ,  1.  ,  3.  ,  0.  ,  5.  ],
        [20.69,  2.45,  0.  ,  1.  ,  1.  ,  4.  ],
        [20.65,  3.35,  1.  ,  1.  ,  1.  ,  3.  ],
        [14.31,  4.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [ 9.55,  1.45,  1.  ,  1.  ,  1.  ,  2.  ],
        [20.9 ,  3.5 ,  0.  ,  2.  ,  1.  ,  3.  ],
        [11.69,  2.31,  1.  ,  3.  ,  0.  ,  2.  ],
        [10.27,  1.71,  1.  ,  2.  ,  1.  ,  2.  ],
        [25.28,  5.  ,  0.  ,  1.  ,  1.  ,  2.  ],
        [16.49,  2.  ,  1.  ,  2.  ,  1.  ,  4.  ],
        [48.17,  5.  ,  1.  ,  2.  ,  1.  ,  6.  ],
        [38.07,  4.  ,  1.  ,  2.  ,  1.  ,  3.  ],
        [ 7.74,  1.44,  1.  ,  1.  ,  1.  ,  2.  ],
        [17.81,  2.34,  1.  ,  1.  ,  1.  ,  4.  ],
        [20.29,  3.21,  1.  ,  1.  ,  1.  ,  2.  ],
        [16.97,  3.5 ,  0.  ,  2.  ,  1.  ,  3.  ],
        [24.08,  2.92,  0.  ,  3.  ,  0.  ,  4.  ],
        [12.03,  1.5 ,  1.  ,  0.  ,  1.  ,  2.  ],
        [43.11,  5.  ,  0.  ,  3.  ,  0.  ,  4.  ],
        [13.16,  2.75,  0.  ,  3.  ,  0.  ,  2.  ],
        [22.67,  2.  ,  1.  ,  1.  ,  1.  ,  2.  ],
        [10.51,  1.25,  1.  ,  1.  ,  1.  ,  2.  ],
        [14.52,  2.  ,  0.  ,  3.  ,  0.  ,  2.  ],
        [23.95,  2.55,  1.  ,  2.  ,  1.  ,  2.  ],
        [10.33,  1.67,  0.  ,  2.  ,  1.  ,  3.  ],
        [10.34,  2.  ,  1.  ,  3.  ,  0.  ,  2.  ],
        [ 3.07,  1.  ,  0.  ,  1.  ,  1.  ,  1.  ],
        [10.59,  1.61,  0.  ,  1.  ,  1.  ,  2.  ],
        [18.69,  2.31,  1.  ,  1.  ,  1.  ,  3.  ],
        [ 7.56,  1.44,  1.  ,  3.  ,  0.  ,  2.  ]]),
 array([[0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1]]),
 array([[0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0]]))

In [ ]:
# 머신러닝 모델링 - 머신러닝 모델링
    # 분류이므로, Regressor 사용
    # 예시: Logistic, KNN, DecisionTree, RandomForest

## 1. Logistic
## 2. KNN

## 3. DecisionTree
# from sklearn.tree import DecisionTreeClassifier
# dtr = DecisionTreeClassifier(max_depth=5)
# dtr.fit(x_train, y_train) # 학습 실행
# dtr.score(x_test, y_test) # 모델의 성능 점수 계산 (R^2 Score)
# 결과: 0.673469387755102. 모델이 0.5보다 높게 예측을 하고 있다는 의미. 괜찮은 수준
# 시사: max_depth을 5, 10, 15 등으로 조정해보기, 더 강력한 모델로 바꾸기
# 변경: max_depth를 5로 설정했더니, 0.7346938775510204. 모델이 0.7보다 높게 예측되었음. 상당히 좋은 수준으로 변경

## 4. RandomForest
from sklearn.ensemble import RandomForestClassifier
rfr = RandomForestClassifier()
rfr.fit(x_train, y_train.ravel()) # .ravel()로 2차원 백터를 1차원으로 변경. Warning 메시지 해결
rfr.score(x_test, y_test.ravel())

# 결과 확인
x_test[0], y_test[0] # 테스트셋의 첫 번째 데이터와 정답 확인. y_test[0] 결과가 0임을 확인
pred = rfr.predict([x_test[0]]) # 만든 RandomForest 모델의 성능이 잘 나오는지 확인
print(pred) # 실제로 0을 예측. 제대로 예측함

[0]